// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-23 15:54:27,  DO NOT EDIT!

#import <Foundation/Foundation.h>

@class MJTestModelStories;
@class MJTestModelTopStories;

@interface MJTestModel : NSObject 
@property (nonatomic, assign) int test;
@property (nonatomic, retain) NSString* date;
@property (nonatomic, retain) NSMutableArray<MJTestModelStories*>*  stories;
@property (nonatomic, retain) NSMutableArray<MJTestModelTopStories*>*  top_stories;
@end


@interface MJTestModelStories : NSObject 
@property (nonatomic, retain) NSMutableArray<NSString*>*  images;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


@interface MJTestModelTopStories : NSObject 
@property (nonatomic, retain) NSString* image;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


