// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-30 09:51:18,  DO NOT EDIT!

#import "MJTestModel.h"

@implementation MJTestModel


-(instancetype)init{
    self = [super init];
    if (self) {
        self.stories = [[NSMutableArray alloc] init];
        self.top_stories = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{
        @"stories" : @"MJTestModel_Stories",
        @"top_stories" : @"MJTestModel_TopStories",

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{

    };
}
@end


@implementation MJTestModel_Stories


-(instancetype)init{
    self = [super init];
    if (self) {
        self.images = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{
        @"images" : @"NSString",

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"ID" : @"id",

    };
}
@end


@implementation MJTestModel_TopStories


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"ID" : @"id",

    };
}
@end


