// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-23 15:54:27,  DO NOT EDIT!

#import <Foundation/Foundation.h>
#import <Mantle/Mantle.h>

@class MTTestModelStories;
@class MTTestModelTopStories;

@interface MTTestModel : MTLModel <MTLJSONSerializing> 
@property (nonatomic, assign) int test;
@property (nonatomic, retain) NSString* date;
@property (nonatomic, retain) NSMutableArray<MTTestModelStories*>*  stories;
@property (nonatomic, retain) NSMutableArray<MTTestModelTopStories*>*  top_stories;
@end


@interface MTTestModelStories : MTLModel <MTLJSONSerializing> 
@property (nonatomic, retain) NSMutableArray<NSString*>*  images;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


@interface MTTestModelTopStories : MTLModel <MTLJSONSerializing> 
@property (nonatomic, retain) NSString* image;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


