// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-23 15:54:27,  DO NOT EDIT!

#import "MTTestModel.h"

@implementation MTTestModel


-(instancetype)init{
    self = [super init];
    if (self) {
        self.stories = [[NSMutableArray alloc] init];
        self.top_stories = [[NSMutableArray alloc] init];

    }
    return self;
}
    

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
   return @{
        @"test" : @"test",
        @"date" : @"date",
        @"stories" : @"stories",
        @"top_stories" : @"top_stories",

    };
}

+ (NSValueTransformer *)storiesJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:MTTestModelStories.class];
}


+ (NSValueTransformer *)top_storiesJSONTransformer {
    return [MTLJSONAdapter arrayTransformerWithModelClass:MTTestModelTopStories.class];
}

@end


@implementation MTTestModelStories


-(instancetype)init{
    self = [super init];
    if (self) {
        self.images = [[NSMutableArray alloc] init];

    }
    return self;
}
    

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
   return @{
        @"images" : @"images",
        @"type" : @"type",
        @"ID" : @"id",
        @"ga_prefix" : @"ga_prefix",
        @"title" : @"title",

    };
}
@end


@implementation MTTestModelTopStories


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    

+ (NSDictionary *)JSONKeyPathsByPropertyKey{
   return @{
        @"image" : @"image",
        @"type" : @"type",
        @"ID" : @"id",
        @"ga_prefix" : @"ga_prefix",
        @"title" : @"title",

    };
}
@end


