// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 16:41:33,  DO NOT EDIT!

#import <Foundation/Foundation.h>
#import <Mantle/Mantle.h>

@class MTTestModel_Stories;
@class MTTestModel_TopStories;

@interface MTTestModel : MTLModel <MTLJSONSerializing> 
@property (nonatomic, assign) int test;
@property (nonatomic, retain) NSString* date;
@property (nonatomic, retain) NSMutableArray<MTTestModel_Stories*>*  stories;
@property (nonatomic, retain) NSMutableArray<MTTestModel_TopStories*>*  top_stories;
@end


@interface MTTestModel_Stories : MTLModel <MTLJSONSerializing> 
@property (nonatomic, retain) NSMutableArray<NSString*>*  images;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


@interface MTTestModel_TopStories : MTLModel <MTLJSONSerializing> 
@property (nonatomic, retain) NSString* image;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


