// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-27 11:27:12,  DO NOT EDIT!

#import "YYTestModel.h"

@implementation YYTestModel


-(instancetype)init{
    self = [super init];
    if (self) {
        self.stories = [[NSMutableArray alloc] init];
        self.top_stories = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)modelContainerPropertyGenericClass{
   return @{
        @"stories" : @"YYTestModel$Stories",
        @"top_stories" : @"YYTestModel$TopStories",

    };
}


+ (NSDictionary *)modelCustomPropertyMapper{
   return @{

    };
}
@end


@implementation YYTestModel$Stories


-(instancetype)init{
    self = [super init];
    if (self) {
        self.images = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)modelContainerPropertyGenericClass{
   return @{
        @"images" : @"NSString",

    };
}


+ (NSDictionary *)modelCustomPropertyMapper{
   return @{
        @"ID" : @"id",

    };
}
@end


@implementation YYTestModel$TopStories


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)modelContainerPropertyGenericClass{
   return @{

    };
}


+ (NSDictionary *)modelCustomPropertyMapper{
   return @{
        @"ID" : @"id",

    };
}
@end


