// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-27 11:27:12,  DO NOT EDIT!

#import <Foundation/Foundation.h>

@class YYTestModel$Stories;
@class YYTestModel$TopStories;

@interface YYTestModel : NSObject 
@property (nonatomic, assign) int test;
@property (nonatomic, retain) NSString* date;
@property (nonatomic, retain) NSMutableArray<YYTestModel$Stories*>*  stories;
@property (nonatomic, retain) NSMutableArray<YYTestModel$TopStories*>*  top_stories;
@end


@interface YYTestModel$Stories : NSObject 
@property (nonatomic, retain) NSMutableArray<NSString*>*  images;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


@interface YYTestModel$TopStories : NSObject 
@property (nonatomic, retain) NSString* image;
@property (nonatomic, assign) int type;
@property (nonatomic, assign) int ID;
@property (nonatomic, retain) NSString* ga_prefix;
@property (nonatomic, retain) NSString* title;
@end


