// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-02 13:37:25,  DO NOT EDIT!

package com.iwanglian;

import java.util.List;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject; 

public class GSTestModel {
	public String resInfo; 
	public int result; 
	public String creditUrl; 

	public static GSTestModel objectFromJSON(JSONObject jsonObject) {
	    GSTestModel object = new GSTestModel(); 
		object.resInfo = jsonObject.optString("res_info");
		object.result = jsonObject.optInt("result");
		object.creditUrl = jsonObject.optString("credit_url");
		return object;
	}
}

