// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-02 15:53:49,  DO NOT EDIT!

package com.iwanglian;

import java.util.List;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject; 

public class GSTestModel {
	public String mResInfo; 
	public int mResult; 
	public String mCreditUrl; 

	public static GSTestModel objectFromJSON(JSONObject jsonObject) {
	    GSTestModel object = new GSTestModel(); 
		object.mResInfo = jsonObject.optString("res_info");
		object.mResult = jsonObject.optInt("result");
		object.mCreditUrl = jsonObject.optString("credit_url");
		return object;
	}
}

