// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 15:21:27,  DO NOT EDIT!

package com.iwanglian;

import java.util.List;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;



public class GSTestModel {
	private String resInfo; 
	private CreditLine creditLine; 
	private int userCardAuthVerifyFlag; 
	private List<MyContent> myContent; 
	private String creditUrl; 
	private int creditImproveStatus; 
	private int result; 
	private int pocketStatus; 
	private int isLogin; 
	private List<PocketOrderInfo> pocketOrderInfo; 

    public static GSTestModel objectFromString(String string) throws JSONException {
        JSONObject jsonObject = new JSONObject(string);
        return objectFromJSON(jsonObject);
    }

    public static String stringFromObject(GSTestModel object) throws JSONException {
        JSONObject jsonObject = JSONFromObject(object);
        return jsonObject.toString();
    }

	public static GSTestModel objectFromJSON(JSONObject jsonObject) {
	    GSTestModel object = new GSTestModel();
	
		object.resInfo = jsonObject.optString("res_info");
		if (jsonObject.optJSONObject("creditLine") != null) {
		    JSONObject jsonObj = jsonObject.optJSONObject("credit_line");
		    object.creditLine = CreditLine.objectFromJSON(jsonObj);
		}
		
		object.userCardAuthVerifyFlag = jsonObject.optInt("user_card_auth_verify_flag");
		if (jsonObject.optJSONArray("my_content") != null) {
		    JSONArray jsonArray = jsonObject.optJSONArray("my_content");
		    List<MyContent> list = new ArrayList<>();
		    for (int i = 0; i < jsonArray.length(); i++) {
				JSONObject jsonObj = jsonArray.optJSONObject(i);
				if(jsonObj!=null) {
				    MyContent item = MyContent.objectFromJSON(jsonObj);
				    list.add(item);
				}
		    }
		    object.myContent = list;
		}
		
		object.creditUrl = jsonObject.optString("credit_url");
		object.creditImproveStatus = jsonObject.optInt("credit_improve_status");
		object.result = jsonObject.optInt("result");
		object.pocketStatus = jsonObject.optInt("pocket_status");
		object.isLogin = jsonObject.optInt("is_login");
		if (jsonObject.optJSONArray("pocket_order_info") != null) {
		    JSONArray jsonArray = jsonObject.optJSONArray("pocket_order_info");
		    List<PocketOrderInfo> list = new ArrayList<>();
		    for (int i = 0; i < jsonArray.length(); i++) {
				JSONObject jsonObj = jsonArray.optJSONObject(i);
				if(jsonObj!=null) {
				    PocketOrderInfo item = PocketOrderInfo.objectFromJSON(jsonObj);
				    list.add(item);
				}
		    }
		    object.pocketOrderInfo = list;
		}
		
		return object;
	}
	
	public static JSONObject JSONFromObject(GSTestModel object) {
	    JSONObject jsonObject = new JSONObject();
	    try { 
			jsonObject.put("res_info", object.resInfo);
			if(object.creditLine != null){
			    JSONObject jsonObj = CreditLine.JSONFromObject(object.creditLine);
			    jsonObject.put("credit_line",jsonObj);
			} 
			jsonObject.put("user_card_auth_verify_flag", object.userCardAuthVerifyFlag);
			if(object.myContent!=null){
			    List<MyContent> list = object.myContent;
			    JSONArray jsonArray = new JSONArray();
				for (MyContent item : list) {
				    JSONObject jsonObj = MyContent.JSONFromObject(item);
				    jsonArray.put(jsonObj);
				} 
			    jsonObject.put("my_content",jsonArray);
			} 
			jsonObject.put("credit_url", object.creditUrl);
			jsonObject.put("credit_improve_status", object.creditImproveStatus);
			jsonObject.put("result", object.result);
			jsonObject.put("pocket_status", object.pocketStatus);
			jsonObject.put("is_login", object.isLogin);
			if(object.pocketOrderInfo!=null){
			    List<PocketOrderInfo> list = object.pocketOrderInfo;
			    JSONArray jsonArray = new JSONArray();
				for (PocketOrderInfo item : list) {
				    JSONObject jsonObj = PocketOrderInfo.JSONFromObject(item);
				    jsonArray.put(jsonObj);
				} 
			    jsonObject.put("pocket_order_info",jsonArray);
			} 
		} catch (JSONException e) {
		    e.printStackTrace();
		}
		
		return jsonObject; 
	}

    public String getResInfo() {
        return resInfo;
    }

    public void setResInfo(String resInfo) {
        this.resInfo = resInfo;
    } 

    public CreditLine getCreditLine() {
        return creditLine;
    }

    public void setCreditLine(CreditLine creditLine) {
        this.creditLine = creditLine;
    } 

    public int getUserCardAuthVerifyFlag() {
        return userCardAuthVerifyFlag;
    }

    public void setUserCardAuthVerifyFlag(int userCardAuthVerifyFlag) {
        this.userCardAuthVerifyFlag = userCardAuthVerifyFlag;
    } 

    public List<MyContent> getMyContent() {
        return myContent;
    }

    public void setMyContent(List<MyContent> myContent) {
        this.myContent = myContent;
    } 

    public String getCreditUrl() {
        return creditUrl;
    }

    public void setCreditUrl(String creditUrl) {
        this.creditUrl = creditUrl;
    } 

    public int getCreditImproveStatus() {
        return creditImproveStatus;
    }

    public void setCreditImproveStatus(int creditImproveStatus) {
        this.creditImproveStatus = creditImproveStatus;
    } 

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    } 

    public int getPocketStatus() {
        return pocketStatus;
    }

    public void setPocketStatus(int pocketStatus) {
        this.pocketStatus = pocketStatus;
    } 

    public int getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(int isLogin) {
        this.isLogin = isLogin;
    } 

    public List<PocketOrderInfo> getPocketOrderInfo() {
        return pocketOrderInfo;
    }

    public void setPocketOrderInfo(List<PocketOrderInfo> pocketOrderInfo) {
        this.pocketOrderInfo = pocketOrderInfo;
    } 

	public static class CreditLine {
		private String pocketAvailableCredit; 
		private String predictGoodsAvlCredit; 
		private String predictPocketAvlCredit; 
		private String resInfo; 
		private String creditLine; 
		private String predictLackCredit; 
		private String goodCredit; 
		private String goodsLackCredit; 
		private String predictPocketLackCredit; 
		private String predictGoodsLackCredit; 
		private String pocketCredit; 
		private String goodsAvailableCredit; 
		private String lackCredit; 
		private String pocketLackCredit; 
		private String availableCreditLine; 
		private String predictAvlCredit; 
		private String predictCredit; 
		private String tempMaxCredit; 
		private String predictPocketCredit; 
		private String predictGoodsCredit; 
		private String result; 
	
		public static CreditLine objectFromJSON(JSONObject jsonObject) {
		    CreditLine object = new CreditLine();
		
			object.pocketAvailableCredit = jsonObject.optString("pocket_available_credit");
			object.predictGoodsAvlCredit = jsonObject.optString("predict_goods_avl_credit");
			object.predictPocketAvlCredit = jsonObject.optString("predict_pocket_avl_credit");
			object.resInfo = jsonObject.optString("res_info");
			object.creditLine = jsonObject.optString("credit_line");
			object.predictLackCredit = jsonObject.optString("predict_lack_credit");
			object.goodCredit = jsonObject.optString("good_credit");
			object.goodsLackCredit = jsonObject.optString("goods_lack_credit");
			object.predictPocketLackCredit = jsonObject.optString("predict_pocket_lack_credit");
			object.predictGoodsLackCredit = jsonObject.optString("predict_goods_lack_credit");
			object.pocketCredit = jsonObject.optString("pocket_credit");
			object.goodsAvailableCredit = jsonObject.optString("goods_available_credit");
			object.lackCredit = jsonObject.optString("lack_credit");
			object.pocketLackCredit = jsonObject.optString("pocket_lack_credit");
			object.availableCreditLine = jsonObject.optString("available_credit_line");
			object.predictAvlCredit = jsonObject.optString("predict_avl_credit");
			object.predictCredit = jsonObject.optString("predict_credit");
			object.tempMaxCredit = jsonObject.optString("temp_max_credit");
			object.predictPocketCredit = jsonObject.optString("predict_pocket_credit");
			object.predictGoodsCredit = jsonObject.optString("predict_goods_credit");
			object.result = jsonObject.optString("result");
			return object;
		}
		
		public static JSONObject JSONFromObject(CreditLine object) {
		    JSONObject jsonObject = new JSONObject();
		    try { 
				jsonObject.put("pocket_available_credit", object.pocketAvailableCredit);
				jsonObject.put("predict_goods_avl_credit", object.predictGoodsAvlCredit);
				jsonObject.put("predict_pocket_avl_credit", object.predictPocketAvlCredit);
				jsonObject.put("res_info", object.resInfo);
				jsonObject.put("credit_line", object.creditLine);
				jsonObject.put("predict_lack_credit", object.predictLackCredit);
				jsonObject.put("good_credit", object.goodCredit);
				jsonObject.put("goods_lack_credit", object.goodsLackCredit);
				jsonObject.put("predict_pocket_lack_credit", object.predictPocketLackCredit);
				jsonObject.put("predict_goods_lack_credit", object.predictGoodsLackCredit);
				jsonObject.put("pocket_credit", object.pocketCredit);
				jsonObject.put("goods_available_credit", object.goodsAvailableCredit);
				jsonObject.put("lack_credit", object.lackCredit);
				jsonObject.put("pocket_lack_credit", object.pocketLackCredit);
				jsonObject.put("available_credit_line", object.availableCreditLine);
				jsonObject.put("predict_avl_credit", object.predictAvlCredit);
				jsonObject.put("predict_credit", object.predictCredit);
				jsonObject.put("temp_max_credit", object.tempMaxCredit);
				jsonObject.put("predict_pocket_credit", object.predictPocketCredit);
				jsonObject.put("predict_goods_credit", object.predictGoodsCredit);
				jsonObject.put("result", object.result);
			} catch (JSONException e) {
			    e.printStackTrace();
			}
			
			return jsonObject; 
		}
	
	    public String getPocketAvailableCredit() {
	        return pocketAvailableCredit;
	    }
	
	    public void setPocketAvailableCredit(String pocketAvailableCredit) {
	        this.pocketAvailableCredit = pocketAvailableCredit;
	    } 
	
	    public String getPredictGoodsAvlCredit() {
	        return predictGoodsAvlCredit;
	    }
	
	    public void setPredictGoodsAvlCredit(String predictGoodsAvlCredit) {
	        this.predictGoodsAvlCredit = predictGoodsAvlCredit;
	    } 
	
	    public String getPredictPocketAvlCredit() {
	        return predictPocketAvlCredit;
	    }
	
	    public void setPredictPocketAvlCredit(String predictPocketAvlCredit) {
	        this.predictPocketAvlCredit = predictPocketAvlCredit;
	    } 
	
	    public String getResInfo() {
	        return resInfo;
	    }
	
	    public void setResInfo(String resInfo) {
	        this.resInfo = resInfo;
	    } 
	
	    public String getCreditLine() {
	        return creditLine;
	    }
	
	    public void setCreditLine(String creditLine) {
	        this.creditLine = creditLine;
	    } 
	
	    public String getPredictLackCredit() {
	        return predictLackCredit;
	    }
	
	    public void setPredictLackCredit(String predictLackCredit) {
	        this.predictLackCredit = predictLackCredit;
	    } 
	
	    public String getGoodCredit() {
	        return goodCredit;
	    }
	
	    public void setGoodCredit(String goodCredit) {
	        this.goodCredit = goodCredit;
	    } 
	
	    public String getGoodsLackCredit() {
	        return goodsLackCredit;
	    }
	
	    public void setGoodsLackCredit(String goodsLackCredit) {
	        this.goodsLackCredit = goodsLackCredit;
	    } 
	
	    public String getPredictPocketLackCredit() {
	        return predictPocketLackCredit;
	    }
	
	    public void setPredictPocketLackCredit(String predictPocketLackCredit) {
	        this.predictPocketLackCredit = predictPocketLackCredit;
	    } 
	
	    public String getPredictGoodsLackCredit() {
	        return predictGoodsLackCredit;
	    }
	
	    public void setPredictGoodsLackCredit(String predictGoodsLackCredit) {
	        this.predictGoodsLackCredit = predictGoodsLackCredit;
	    } 
	
	    public String getPocketCredit() {
	        return pocketCredit;
	    }
	
	    public void setPocketCredit(String pocketCredit) {
	        this.pocketCredit = pocketCredit;
	    } 
	
	    public String getGoodsAvailableCredit() {
	        return goodsAvailableCredit;
	    }
	
	    public void setGoodsAvailableCredit(String goodsAvailableCredit) {
	        this.goodsAvailableCredit = goodsAvailableCredit;
	    } 
	
	    public String getLackCredit() {
	        return lackCredit;
	    }
	
	    public void setLackCredit(String lackCredit) {
	        this.lackCredit = lackCredit;
	    } 
	
	    public String getPocketLackCredit() {
	        return pocketLackCredit;
	    }
	
	    public void setPocketLackCredit(String pocketLackCredit) {
	        this.pocketLackCredit = pocketLackCredit;
	    } 
	
	    public String getAvailableCreditLine() {
	        return availableCreditLine;
	    }
	
	    public void setAvailableCreditLine(String availableCreditLine) {
	        this.availableCreditLine = availableCreditLine;
	    } 
	
	    public String getPredictAvlCredit() {
	        return predictAvlCredit;
	    }
	
	    public void setPredictAvlCredit(String predictAvlCredit) {
	        this.predictAvlCredit = predictAvlCredit;
	    } 
	
	    public String getPredictCredit() {
	        return predictCredit;
	    }
	
	    public void setPredictCredit(String predictCredit) {
	        this.predictCredit = predictCredit;
	    } 
	
	    public String getTempMaxCredit() {
	        return tempMaxCredit;
	    }
	
	    public void setTempMaxCredit(String tempMaxCredit) {
	        this.tempMaxCredit = tempMaxCredit;
	    } 
	
	    public String getPredictPocketCredit() {
	        return predictPocketCredit;
	    }
	
	    public void setPredictPocketCredit(String predictPocketCredit) {
	        this.predictPocketCredit = predictPocketCredit;
	    } 
	
	    public String getPredictGoodsCredit() {
	        return predictGoodsCredit;
	    }
	
	    public void setPredictGoodsCredit(String predictGoodsCredit) {
	        this.predictGoodsCredit = predictGoodsCredit;
	    } 
	
	    public String getResult() {
	        return result;
	    }
	
	    public void setResult(String result) {
	        this.result = result;
	    } 
	}
	

	public static class MyContent {
		private String canAppShow; 
		private String needRedDot; 
		private String title; 
		private String url; 
		private String tipImgUrl; 
		private String tipText; 
		private String tipVisible; 
		private String configKey; 
		private String key; 
		private String h5Enabled; 
		private String imgUrl; 
		private String canH5Show; 
	
		public static MyContent objectFromJSON(JSONObject jsonObject) {
		    MyContent object = new MyContent();
		
			object.canAppShow = jsonObject.optString("can_app_show");
			object.needRedDot = jsonObject.optString("need_red_dot");
			object.title = jsonObject.optString("title");
			object.url = jsonObject.optString("url");
			object.tipImgUrl = jsonObject.optString("tip_img_url");
			object.tipText = jsonObject.optString("tip_text");
			object.tipVisible = jsonObject.optString("tip_visible");
			object.configKey = jsonObject.optString("config_key");
			object.key = jsonObject.optString("key");
			object.h5Enabled = jsonObject.optString("h5_enabled");
			object.imgUrl = jsonObject.optString("img_url");
			object.canH5Show = jsonObject.optString("can_h5_show");
			return object;
		}
		
		public static JSONObject JSONFromObject(MyContent object) {
		    JSONObject jsonObject = new JSONObject();
		    try { 
				jsonObject.put("can_app_show", object.canAppShow);
				jsonObject.put("need_red_dot", object.needRedDot);
				jsonObject.put("title", object.title);
				jsonObject.put("url", object.url);
				jsonObject.put("tip_img_url", object.tipImgUrl);
				jsonObject.put("tip_text", object.tipText);
				jsonObject.put("tip_visible", object.tipVisible);
				jsonObject.put("config_key", object.configKey);
				jsonObject.put("key", object.key);
				jsonObject.put("h5_enabled", object.h5Enabled);
				jsonObject.put("img_url", object.imgUrl);
				jsonObject.put("can_h5_show", object.canH5Show);
			} catch (JSONException e) {
			    e.printStackTrace();
			}
			
			return jsonObject; 
		}
	
	    public String getCanAppShow() {
	        return canAppShow;
	    }
	
	    public void setCanAppShow(String canAppShow) {
	        this.canAppShow = canAppShow;
	    } 
	
	    public String getNeedRedDot() {
	        return needRedDot;
	    }
	
	    public void setNeedRedDot(String needRedDot) {
	        this.needRedDot = needRedDot;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	
	    public String getUrl() {
	        return url;
	    }
	
	    public void setUrl(String url) {
	        this.url = url;
	    } 
	
	    public String getTipImgUrl() {
	        return tipImgUrl;
	    }
	
	    public void setTipImgUrl(String tipImgUrl) {
	        this.tipImgUrl = tipImgUrl;
	    } 
	
	    public String getTipText() {
	        return tipText;
	    }
	
	    public void setTipText(String tipText) {
	        this.tipText = tipText;
	    } 
	
	    public String getTipVisible() {
	        return tipVisible;
	    }
	
	    public void setTipVisible(String tipVisible) {
	        this.tipVisible = tipVisible;
	    } 
	
	    public String getConfigKey() {
	        return configKey;
	    }
	
	    public void setConfigKey(String configKey) {
	        this.configKey = configKey;
	    } 
	
	    public String getKey() {
	        return key;
	    }
	
	    public void setKey(String key) {
	        this.key = key;
	    } 
	
	    public String getH5Enabled() {
	        return h5Enabled;
	    }
	
	    public void setH5Enabled(String h5Enabled) {
	        this.h5Enabled = h5Enabled;
	    } 
	
	    public String getImgUrl() {
	        return imgUrl;
	    }
	
	    public void setImgUrl(String imgUrl) {
	        this.imgUrl = imgUrl;
	    } 
	
	    public String getCanH5Show() {
	        return canH5Show;
	    }
	
	    public void setCanH5Show(String canH5Show) {
	        this.canH5Show = canH5Show;
	    } 
	}
	

	public static class PocketOrderInfo {
		private String assistedPic4; 
		private String assistedPic5; 
		private String areaId; 
		private String assistedPic7; 
		private String assistedPic1; 
		private String assistedPic2; 
		private String assistedPic3; 
		private String cityId; 
		private String laborHomePic; 
		private String assistedPic8; 
		private String assistedPic6; 
		private String orderDeliveryMobile; 
		private int isCloseFlag; 
		private String factoryId; 
		private int orderExReturnFlag; 
		private String creditBack; 
		private int totalMonPay; 
		private String phoneTime; 
		private int submitCloseFlag; 
		private int orderFinishFlag; 
		private int orderExExpressFlag; 
		private int orderExFinishFlag; 
		private String city; 
		private String entryTime; 
		private int canEvaSku; 
		private int hideFlag; 
		private List<OrderInfo> orderInfo; 
		private String assistedPic9; 
		private int isEditFlag; 
		private String orderState; 
		private int discountAmount; 
		private String waterElectronicPaymentPic; 
		private String school; 
		private String exResultInfo; 
		private String name; 
		private String maritalStatus; 
		private String provinceName; 
		private String orderAuthTypeDesc; 
		private boolean isShowBuyFlag; 
		private String innerFlag; 
		private String pensionDetailPic; 
		private String province; 
		private int nondeliveryFlag; 
		private String phoneTimeDesc; 
		private int waitAuthChooseFlag; 
		private String receiverId; 
		private String monRepayDay; 
		private String createTime; 
		private String exId; 
		private String orderDeliveryName; 
		private int experienceGoldFlag; 
		private String extInfoJson; 
		private String firstName; 
		private String discountId; 
		private int canEvaDelivery; 
		private int totalMonFee; 
		private boolean isShowPayFlag; 
		private String laborSignaturePic; 
		private String creditId; 
		private int isCancelFlag; 
		private String receiptMobile; 
		private String payType; 
		private String orderId; 
		private String jobProofPic; 
		private String orderStateDesc; 
		private String jdAccountName; 
		private String eduLevel; 
		private int fiftyPercentOffFlag; 
		private String employStatus; 
		private String address; 
		private String dorm; 
		private int canCheckFlag; 
		private String assistedPic10; 
		private String maxFqNum; 
		private String deliveryAddress; 
		private int totalAmount; 
		private int commentFlag; 
		private String bankType; 
		private int urgeOrderFlag; 
		private String modifyTime; 
		private int canSubmitFlag; 
		private String repayNum; 
		private String subFactoryId; 
		private int payFirstpayFlag; 
		private int consumeFlag; 
		private String county; 
		private int orderOutReturn; 
		private String nextRepayDay; 
		private int checkSubmitFlag; 
		private int staffFlag; 
		private String area; 
		private int totalManageFee; 
		private int repayListShowFlag; 
		private String badgePic; 
		private int orderAuthType; 
		private String maritalStatusDesc; 
		private String schoolId; 
		private String receiptMobileEcp; 
		private String creditLineType; 
		private String saleType; 
		private int receiveType; 
		private String userType; 
		private String delivery; 
		private String receiveTypeDesc; 
		private int totalFirstpay; 
		private String provinceId; 
		private String creditIdEcp; 
		private int finishTradeFlag; 
		private int reduceAmount; 
		private int orderStateEx; 
		private String scenePic; 
		private String uid; 
		private int rebutFlag; 
		private int exState; 
		private String repayType; 
		private int experienceGold; 
		private String factoryName; 
		private String subFactoryName; 
		private String monthlySalary; 
		private String countyId; 
		private String saleTypeDesc; 
		private String accountDate; 
		private String orderType; 
		private String incomePayrollPic1; 
		private String payStateDesc; 
		private String creditFront; 
		private int inAfterSale; 
		private String eduLevelDesc; 
		private String department; 
		private String positionDesc; 
		private String payState; 
		private String checkResult; 
		private String deliveryMobile; 
		private String factoryTel; 
		private int testFlag; 
		private String userSubtype; 
		private int isDrawFailedFlag; 
		private String cityName; 
		private int orderOutEx; 
		private String incomePayrollPic2; 
		private String socialSecurityDetailPic; 
		private int totalCapital; 
		private int selfValidateFlag; 
		private String arriveTime; 
		private int totalHandlingFee; 
		private int orderExCancelFlag; 
		private String position; 
	
		public static PocketOrderInfo objectFromJSON(JSONObject jsonObject) {
		    PocketOrderInfo object = new PocketOrderInfo();
		
			object.assistedPic4 = jsonObject.optString("assisted_pic_4");
			object.assistedPic5 = jsonObject.optString("assisted_pic_5");
			object.areaId = jsonObject.optString("area_id");
			object.assistedPic7 = jsonObject.optString("assisted_pic_7");
			object.assistedPic1 = jsonObject.optString("assisted_pic_1");
			object.assistedPic2 = jsonObject.optString("assisted_pic_2");
			object.assistedPic3 = jsonObject.optString("assisted_pic_3");
			object.cityId = jsonObject.optString("city_id");
			object.laborHomePic = jsonObject.optString("labor_home_pic");
			object.assistedPic8 = jsonObject.optString("assisted_pic_8");
			object.assistedPic6 = jsonObject.optString("assisted_pic_6");
			object.orderDeliveryMobile = jsonObject.optString("order_delivery_mobile");
			object.isCloseFlag = jsonObject.optInt("is_close_flag");
			object.factoryId = jsonObject.optString("factory_id");
			object.orderExReturnFlag = jsonObject.optInt("order_ex_return_flag");
			object.creditBack = jsonObject.optString("credit_back");
			object.totalMonPay = jsonObject.optInt("total_mon_pay");
			object.phoneTime = jsonObject.optString("phone_time");
			object.submitCloseFlag = jsonObject.optInt("submit_close_flag");
			object.orderFinishFlag = jsonObject.optInt("order_finish_flag");
			object.orderExExpressFlag = jsonObject.optInt("order_ex_express_flag");
			object.orderExFinishFlag = jsonObject.optInt("order_ex_finish_flag");
			object.city = jsonObject.optString("city");
			object.entryTime = jsonObject.optString("entry_time");
			object.canEvaSku = jsonObject.optInt("can_eva_sku");
			object.hideFlag = jsonObject.optInt("hide_flag");
			if (jsonObject.optJSONArray("order_info") != null) {
			    JSONArray jsonArray = jsonObject.optJSONArray("order_info");
			    List<OrderInfo> list = new ArrayList<>();
			    for (int i = 0; i < jsonArray.length(); i++) {
					JSONObject jsonObj = jsonArray.optJSONObject(i);
					if(jsonObj!=null) {
					    OrderInfo item = OrderInfo.objectFromJSON(jsonObj);
					    list.add(item);
					}
			    }
			    object.orderInfo = list;
			}
			
			object.assistedPic9 = jsonObject.optString("assisted_pic_9");
			object.isEditFlag = jsonObject.optInt("is_edit_flag");
			object.orderState = jsonObject.optString("order_state");
			object.discountAmount = jsonObject.optInt("discount_amount");
			object.waterElectronicPaymentPic = jsonObject.optString("water_electronic_payment_pic");
			object.school = jsonObject.optString("school");
			object.exResultInfo = jsonObject.optString("ex_result_info");
			object.name = jsonObject.optString("name");
			object.maritalStatus = jsonObject.optString("marital_status");
			object.provinceName = jsonObject.optString("province_name");
			object.orderAuthTypeDesc = jsonObject.optString("order_auth_type_desc");
			object.isShowBuyFlag = jsonObject.optBoolean("is_show_buy_flag");
			object.innerFlag = jsonObject.optString("inner_flag");
			object.pensionDetailPic = jsonObject.optString("pension_detail_pic");
			object.province = jsonObject.optString("province");
			object.nondeliveryFlag = jsonObject.optInt("nondelivery_flag");
			object.phoneTimeDesc = jsonObject.optString("phone_time_desc");
			object.waitAuthChooseFlag = jsonObject.optInt("wait_auth_choose_flag");
			object.receiverId = jsonObject.optString("receiver_id");
			object.monRepayDay = jsonObject.optString("mon_repay_day");
			object.createTime = jsonObject.optString("create_time");
			object.exId = jsonObject.optString("ex_id");
			object.orderDeliveryName = jsonObject.optString("order_delivery_name");
			object.experienceGoldFlag = jsonObject.optInt("experience_gold_flag");
			object.extInfoJson = jsonObject.optString("ext_info_json");
			object.firstName = jsonObject.optString("first_name");
			object.discountId = jsonObject.optString("discount_id");
			object.canEvaDelivery = jsonObject.optInt("can_eva_delivery");
			object.totalMonFee = jsonObject.optInt("total_mon_fee");
			object.isShowPayFlag = jsonObject.optBoolean("is_show_pay_flag");
			object.laborSignaturePic = jsonObject.optString("labor_signature_pic");
			object.creditId = jsonObject.optString("credit_id");
			object.isCancelFlag = jsonObject.optInt("is_cancel_flag");
			object.receiptMobile = jsonObject.optString("receipt_mobile");
			object.payType = jsonObject.optString("pay_type");
			object.orderId = jsonObject.optString("order_id");
			object.jobProofPic = jsonObject.optString("job_proof_pic");
			object.orderStateDesc = jsonObject.optString("order_state_desc");
			object.jdAccountName = jsonObject.optString("jd_account_name");
			object.eduLevel = jsonObject.optString("edu_level");
			object.fiftyPercentOffFlag = jsonObject.optInt("fifty_percent_off_flag");
			object.employStatus = jsonObject.optString("employ_status");
			object.address = jsonObject.optString("address");
			object.dorm = jsonObject.optString("dorm");
			object.canCheckFlag = jsonObject.optInt("can_check_flag");
			object.assistedPic10 = jsonObject.optString("assisted_pic_10");
			object.maxFqNum = jsonObject.optString("max_fq_num");
			object.deliveryAddress = jsonObject.optString("delivery_address");
			object.totalAmount = jsonObject.optInt("total_amount");
			object.commentFlag = jsonObject.optInt("comment_flag");
			object.bankType = jsonObject.optString("bank_type");
			object.urgeOrderFlag = jsonObject.optInt("urge_order_flag");
			object.modifyTime = jsonObject.optString("modify_time");
			object.canSubmitFlag = jsonObject.optInt("can_submit_flag");
			object.repayNum = jsonObject.optString("repay_num");
			object.subFactoryId = jsonObject.optString("sub_factory_id");
			object.payFirstpayFlag = jsonObject.optInt("pay_firstpay_flag");
			object.consumeFlag = jsonObject.optInt("consume_flag");
			object.county = jsonObject.optString("county");
			object.orderOutReturn = jsonObject.optInt("order_out_return");
			object.nextRepayDay = jsonObject.optString("next_repay_day");
			object.checkSubmitFlag = jsonObject.optInt("check_submit_flag");
			object.staffFlag = jsonObject.optInt("staff_flag");
			object.area = jsonObject.optString("area");
			object.totalManageFee = jsonObject.optInt("total_manage_fee");
			object.repayListShowFlag = jsonObject.optInt("repay_list_show_flag");
			object.badgePic = jsonObject.optString("badge_pic");
			object.orderAuthType = jsonObject.optInt("order_auth_type");
			object.maritalStatusDesc = jsonObject.optString("marital_status_desc");
			object.schoolId = jsonObject.optString("school_id");
			object.receiptMobileEcp = jsonObject.optString("receipt_mobile_ecp");
			object.creditLineType = jsonObject.optString("credit_line_type");
			object.saleType = jsonObject.optString("sale_type");
			object.receiveType = jsonObject.optInt("receive_type");
			object.userType = jsonObject.optString("user_type");
			object.delivery = jsonObject.optString("delivery");
			object.receiveTypeDesc = jsonObject.optString("receive_type_desc");
			object.totalFirstpay = jsonObject.optInt("total_firstpay");
			object.provinceId = jsonObject.optString("province_id");
			object.creditIdEcp = jsonObject.optString("credit_id_ecp");
			object.finishTradeFlag = jsonObject.optInt("finish_trade_flag");
			object.reduceAmount = jsonObject.optInt("reduce_amount");
			object.orderStateEx = jsonObject.optInt("order_state_ex");
			object.scenePic = jsonObject.optString("scene_pic");
			object.uid = jsonObject.optString("uid");
			object.rebutFlag = jsonObject.optInt("rebut_flag");
			object.exState = jsonObject.optInt("ex_state");
			object.repayType = jsonObject.optString("repay_type");
			object.experienceGold = jsonObject.optInt("experience_gold");
			object.factoryName = jsonObject.optString("factory_name");
			object.subFactoryName = jsonObject.optString("sub_factory_name");
			object.monthlySalary = jsonObject.optString("monthly_salary");
			object.countyId = jsonObject.optString("county_id");
			object.saleTypeDesc = jsonObject.optString("sale_type_desc");
			object.accountDate = jsonObject.optString("account_date");
			object.orderType = jsonObject.optString("order_type");
			object.incomePayrollPic1 = jsonObject.optString("income_payroll_pic_1");
			object.payStateDesc = jsonObject.optString("pay_state_desc");
			object.creditFront = jsonObject.optString("credit_front");
			object.inAfterSale = jsonObject.optInt("in_after_sale");
			object.eduLevelDesc = jsonObject.optString("edu_level_desc");
			object.department = jsonObject.optString("department");
			object.positionDesc = jsonObject.optString("position_desc");
			object.payState = jsonObject.optString("pay_state");
			object.checkResult = jsonObject.optString("check_result");
			object.deliveryMobile = jsonObject.optString("delivery_mobile");
			object.factoryTel = jsonObject.optString("factory_tel");
			object.testFlag = jsonObject.optInt("test_flag");
			object.userSubtype = jsonObject.optString("user_subtype");
			object.isDrawFailedFlag = jsonObject.optInt("is_draw_failed_flag");
			object.cityName = jsonObject.optString("city_name");
			object.orderOutEx = jsonObject.optInt("order_out_ex");
			object.incomePayrollPic2 = jsonObject.optString("income_payroll_pic_2");
			object.socialSecurityDetailPic = jsonObject.optString("social_security_detail_pic");
			object.totalCapital = jsonObject.optInt("total_capital");
			object.selfValidateFlag = jsonObject.optInt("self_validate_flag");
			object.arriveTime = jsonObject.optString("arrive_time");
			object.totalHandlingFee = jsonObject.optInt("total_handling_fee");
			object.orderExCancelFlag = jsonObject.optInt("order_ex_cancel_flag");
			object.position = jsonObject.optString("position");
			return object;
		}
		
		public static JSONObject JSONFromObject(PocketOrderInfo object) {
		    JSONObject jsonObject = new JSONObject();
		    try { 
				jsonObject.put("assisted_pic_4", object.assistedPic4);
				jsonObject.put("assisted_pic_5", object.assistedPic5);
				jsonObject.put("area_id", object.areaId);
				jsonObject.put("assisted_pic_7", object.assistedPic7);
				jsonObject.put("assisted_pic_1", object.assistedPic1);
				jsonObject.put("assisted_pic_2", object.assistedPic2);
				jsonObject.put("assisted_pic_3", object.assistedPic3);
				jsonObject.put("city_id", object.cityId);
				jsonObject.put("labor_home_pic", object.laborHomePic);
				jsonObject.put("assisted_pic_8", object.assistedPic8);
				jsonObject.put("assisted_pic_6", object.assistedPic6);
				jsonObject.put("order_delivery_mobile", object.orderDeliveryMobile);
				jsonObject.put("is_close_flag", object.isCloseFlag);
				jsonObject.put("factory_id", object.factoryId);
				jsonObject.put("order_ex_return_flag", object.orderExReturnFlag);
				jsonObject.put("credit_back", object.creditBack);
				jsonObject.put("total_mon_pay", object.totalMonPay);
				jsonObject.put("phone_time", object.phoneTime);
				jsonObject.put("submit_close_flag", object.submitCloseFlag);
				jsonObject.put("order_finish_flag", object.orderFinishFlag);
				jsonObject.put("order_ex_express_flag", object.orderExExpressFlag);
				jsonObject.put("order_ex_finish_flag", object.orderExFinishFlag);
				jsonObject.put("city", object.city);
				jsonObject.put("entry_time", object.entryTime);
				jsonObject.put("can_eva_sku", object.canEvaSku);
				jsonObject.put("hide_flag", object.hideFlag);
				if(object.orderInfo!=null){
				    List<OrderInfo> list = object.orderInfo;
				    JSONArray jsonArray = new JSONArray();
					for (OrderInfo item : list) {
					    JSONObject jsonObj = OrderInfo.JSONFromObject(item);
					    jsonArray.put(jsonObj);
					} 
				    jsonObject.put("order_info",jsonArray);
				} 
				jsonObject.put("assisted_pic_9", object.assistedPic9);
				jsonObject.put("is_edit_flag", object.isEditFlag);
				jsonObject.put("order_state", object.orderState);
				jsonObject.put("discount_amount", object.discountAmount);
				jsonObject.put("water_electronic_payment_pic", object.waterElectronicPaymentPic);
				jsonObject.put("school", object.school);
				jsonObject.put("ex_result_info", object.exResultInfo);
				jsonObject.put("name", object.name);
				jsonObject.put("marital_status", object.maritalStatus);
				jsonObject.put("province_name", object.provinceName);
				jsonObject.put("order_auth_type_desc", object.orderAuthTypeDesc);
				jsonObject.put("is_show_buy_flag", object.isShowBuyFlag);
				jsonObject.put("inner_flag", object.innerFlag);
				jsonObject.put("pension_detail_pic", object.pensionDetailPic);
				jsonObject.put("province", object.province);
				jsonObject.put("nondelivery_flag", object.nondeliveryFlag);
				jsonObject.put("phone_time_desc", object.phoneTimeDesc);
				jsonObject.put("wait_auth_choose_flag", object.waitAuthChooseFlag);
				jsonObject.put("receiver_id", object.receiverId);
				jsonObject.put("mon_repay_day", object.monRepayDay);
				jsonObject.put("create_time", object.createTime);
				jsonObject.put("ex_id", object.exId);
				jsonObject.put("order_delivery_name", object.orderDeliveryName);
				jsonObject.put("experience_gold_flag", object.experienceGoldFlag);
				jsonObject.put("ext_info_json", object.extInfoJson);
				jsonObject.put("first_name", object.firstName);
				jsonObject.put("discount_id", object.discountId);
				jsonObject.put("can_eva_delivery", object.canEvaDelivery);
				jsonObject.put("total_mon_fee", object.totalMonFee);
				jsonObject.put("is_show_pay_flag", object.isShowPayFlag);
				jsonObject.put("labor_signature_pic", object.laborSignaturePic);
				jsonObject.put("credit_id", object.creditId);
				jsonObject.put("is_cancel_flag", object.isCancelFlag);
				jsonObject.put("receipt_mobile", object.receiptMobile);
				jsonObject.put("pay_type", object.payType);
				jsonObject.put("order_id", object.orderId);
				jsonObject.put("job_proof_pic", object.jobProofPic);
				jsonObject.put("order_state_desc", object.orderStateDesc);
				jsonObject.put("jd_account_name", object.jdAccountName);
				jsonObject.put("edu_level", object.eduLevel);
				jsonObject.put("fifty_percent_off_flag", object.fiftyPercentOffFlag);
				jsonObject.put("employ_status", object.employStatus);
				jsonObject.put("address", object.address);
				jsonObject.put("dorm", object.dorm);
				jsonObject.put("can_check_flag", object.canCheckFlag);
				jsonObject.put("assisted_pic_10", object.assistedPic10);
				jsonObject.put("max_fq_num", object.maxFqNum);
				jsonObject.put("delivery_address", object.deliveryAddress);
				jsonObject.put("total_amount", object.totalAmount);
				jsonObject.put("comment_flag", object.commentFlag);
				jsonObject.put("bank_type", object.bankType);
				jsonObject.put("urge_order_flag", object.urgeOrderFlag);
				jsonObject.put("modify_time", object.modifyTime);
				jsonObject.put("can_submit_flag", object.canSubmitFlag);
				jsonObject.put("repay_num", object.repayNum);
				jsonObject.put("sub_factory_id", object.subFactoryId);
				jsonObject.put("pay_firstpay_flag", object.payFirstpayFlag);
				jsonObject.put("consume_flag", object.consumeFlag);
				jsonObject.put("county", object.county);
				jsonObject.put("order_out_return", object.orderOutReturn);
				jsonObject.put("next_repay_day", object.nextRepayDay);
				jsonObject.put("check_submit_flag", object.checkSubmitFlag);
				jsonObject.put("staff_flag", object.staffFlag);
				jsonObject.put("area", object.area);
				jsonObject.put("total_manage_fee", object.totalManageFee);
				jsonObject.put("repay_list_show_flag", object.repayListShowFlag);
				jsonObject.put("badge_pic", object.badgePic);
				jsonObject.put("order_auth_type", object.orderAuthType);
				jsonObject.put("marital_status_desc", object.maritalStatusDesc);
				jsonObject.put("school_id", object.schoolId);
				jsonObject.put("receipt_mobile_ecp", object.receiptMobileEcp);
				jsonObject.put("credit_line_type", object.creditLineType);
				jsonObject.put("sale_type", object.saleType);
				jsonObject.put("receive_type", object.receiveType);
				jsonObject.put("user_type", object.userType);
				jsonObject.put("delivery", object.delivery);
				jsonObject.put("receive_type_desc", object.receiveTypeDesc);
				jsonObject.put("total_firstpay", object.totalFirstpay);
				jsonObject.put("province_id", object.provinceId);
				jsonObject.put("credit_id_ecp", object.creditIdEcp);
				jsonObject.put("finish_trade_flag", object.finishTradeFlag);
				jsonObject.put("reduce_amount", object.reduceAmount);
				jsonObject.put("order_state_ex", object.orderStateEx);
				jsonObject.put("scene_pic", object.scenePic);
				jsonObject.put("uid", object.uid);
				jsonObject.put("rebut_flag", object.rebutFlag);
				jsonObject.put("ex_state", object.exState);
				jsonObject.put("repay_type", object.repayType);
				jsonObject.put("experience_gold", object.experienceGold);
				jsonObject.put("factory_name", object.factoryName);
				jsonObject.put("sub_factory_name", object.subFactoryName);
				jsonObject.put("monthly_salary", object.monthlySalary);
				jsonObject.put("county_id", object.countyId);
				jsonObject.put("sale_type_desc", object.saleTypeDesc);
				jsonObject.put("account_date", object.accountDate);
				jsonObject.put("order_type", object.orderType);
				jsonObject.put("income_payroll_pic_1", object.incomePayrollPic1);
				jsonObject.put("pay_state_desc", object.payStateDesc);
				jsonObject.put("credit_front", object.creditFront);
				jsonObject.put("in_after_sale", object.inAfterSale);
				jsonObject.put("edu_level_desc", object.eduLevelDesc);
				jsonObject.put("department", object.department);
				jsonObject.put("position_desc", object.positionDesc);
				jsonObject.put("pay_state", object.payState);
				jsonObject.put("check_result", object.checkResult);
				jsonObject.put("delivery_mobile", object.deliveryMobile);
				jsonObject.put("factory_tel", object.factoryTel);
				jsonObject.put("test_flag", object.testFlag);
				jsonObject.put("user_subtype", object.userSubtype);
				jsonObject.put("is_draw_failed_flag", object.isDrawFailedFlag);
				jsonObject.put("city_name", object.cityName);
				jsonObject.put("order_out_ex", object.orderOutEx);
				jsonObject.put("income_payroll_pic_2", object.incomePayrollPic2);
				jsonObject.put("social_security_detail_pic", object.socialSecurityDetailPic);
				jsonObject.put("total_capital", object.totalCapital);
				jsonObject.put("self_validate_flag", object.selfValidateFlag);
				jsonObject.put("arrive_time", object.arriveTime);
				jsonObject.put("total_handling_fee", object.totalHandlingFee);
				jsonObject.put("order_ex_cancel_flag", object.orderExCancelFlag);
				jsonObject.put("position", object.position);
			} catch (JSONException e) {
			    e.printStackTrace();
			}
			
			return jsonObject; 
		}
	
	    public String getAssistedPic4() {
	        return assistedPic4;
	    }
	
	    public void setAssistedPic4(String assistedPic4) {
	        this.assistedPic4 = assistedPic4;
	    } 
	
	    public String getAssistedPic5() {
	        return assistedPic5;
	    }
	
	    public void setAssistedPic5(String assistedPic5) {
	        this.assistedPic5 = assistedPic5;
	    } 
	
	    public String getAreaId() {
	        return areaId;
	    }
	
	    public void setAreaId(String areaId) {
	        this.areaId = areaId;
	    } 
	
	    public String getAssistedPic7() {
	        return assistedPic7;
	    }
	
	    public void setAssistedPic7(String assistedPic7) {
	        this.assistedPic7 = assistedPic7;
	    } 
	
	    public String getAssistedPic1() {
	        return assistedPic1;
	    }
	
	    public void setAssistedPic1(String assistedPic1) {
	        this.assistedPic1 = assistedPic1;
	    } 
	
	    public String getAssistedPic2() {
	        return assistedPic2;
	    }
	
	    public void setAssistedPic2(String assistedPic2) {
	        this.assistedPic2 = assistedPic2;
	    } 
	
	    public String getAssistedPic3() {
	        return assistedPic3;
	    }
	
	    public void setAssistedPic3(String assistedPic3) {
	        this.assistedPic3 = assistedPic3;
	    } 
	
	    public String getCityId() {
	        return cityId;
	    }
	
	    public void setCityId(String cityId) {
	        this.cityId = cityId;
	    } 
	
	    public String getLaborHomePic() {
	        return laborHomePic;
	    }
	
	    public void setLaborHomePic(String laborHomePic) {
	        this.laborHomePic = laborHomePic;
	    } 
	
	    public String getAssistedPic8() {
	        return assistedPic8;
	    }
	
	    public void setAssistedPic8(String assistedPic8) {
	        this.assistedPic8 = assistedPic8;
	    } 
	
	    public String getAssistedPic6() {
	        return assistedPic6;
	    }
	
	    public void setAssistedPic6(String assistedPic6) {
	        this.assistedPic6 = assistedPic6;
	    } 
	
	    public String getOrderDeliveryMobile() {
	        return orderDeliveryMobile;
	    }
	
	    public void setOrderDeliveryMobile(String orderDeliveryMobile) {
	        this.orderDeliveryMobile = orderDeliveryMobile;
	    } 
	
	    public int getIsCloseFlag() {
	        return isCloseFlag;
	    }
	
	    public void setIsCloseFlag(int isCloseFlag) {
	        this.isCloseFlag = isCloseFlag;
	    } 
	
	    public String getFactoryId() {
	        return factoryId;
	    }
	
	    public void setFactoryId(String factoryId) {
	        this.factoryId = factoryId;
	    } 
	
	    public int getOrderExReturnFlag() {
	        return orderExReturnFlag;
	    }
	
	    public void setOrderExReturnFlag(int orderExReturnFlag) {
	        this.orderExReturnFlag = orderExReturnFlag;
	    } 
	
	    public String getCreditBack() {
	        return creditBack;
	    }
	
	    public void setCreditBack(String creditBack) {
	        this.creditBack = creditBack;
	    } 
	
	    public int getTotalMonPay() {
	        return totalMonPay;
	    }
	
	    public void setTotalMonPay(int totalMonPay) {
	        this.totalMonPay = totalMonPay;
	    } 
	
	    public String getPhoneTime() {
	        return phoneTime;
	    }
	
	    public void setPhoneTime(String phoneTime) {
	        this.phoneTime = phoneTime;
	    } 
	
	    public int getSubmitCloseFlag() {
	        return submitCloseFlag;
	    }
	
	    public void setSubmitCloseFlag(int submitCloseFlag) {
	        this.submitCloseFlag = submitCloseFlag;
	    } 
	
	    public int getOrderFinishFlag() {
	        return orderFinishFlag;
	    }
	
	    public void setOrderFinishFlag(int orderFinishFlag) {
	        this.orderFinishFlag = orderFinishFlag;
	    } 
	
	    public int getOrderExExpressFlag() {
	        return orderExExpressFlag;
	    }
	
	    public void setOrderExExpressFlag(int orderExExpressFlag) {
	        this.orderExExpressFlag = orderExExpressFlag;
	    } 
	
	    public int getOrderExFinishFlag() {
	        return orderExFinishFlag;
	    }
	
	    public void setOrderExFinishFlag(int orderExFinishFlag) {
	        this.orderExFinishFlag = orderExFinishFlag;
	    } 
	
	    public String getCity() {
	        return city;
	    }
	
	    public void setCity(String city) {
	        this.city = city;
	    } 
	
	    public String getEntryTime() {
	        return entryTime;
	    }
	
	    public void setEntryTime(String entryTime) {
	        this.entryTime = entryTime;
	    } 
	
	    public int getCanEvaSku() {
	        return canEvaSku;
	    }
	
	    public void setCanEvaSku(int canEvaSku) {
	        this.canEvaSku = canEvaSku;
	    } 
	
	    public int getHideFlag() {
	        return hideFlag;
	    }
	
	    public void setHideFlag(int hideFlag) {
	        this.hideFlag = hideFlag;
	    } 
	
	    public List<OrderInfo> getOrderInfo() {
	        return orderInfo;
	    }
	
	    public void setOrderInfo(List<OrderInfo> orderInfo) {
	        this.orderInfo = orderInfo;
	    } 
	
	    public String getAssistedPic9() {
	        return assistedPic9;
	    }
	
	    public void setAssistedPic9(String assistedPic9) {
	        this.assistedPic9 = assistedPic9;
	    } 
	
	    public int getIsEditFlag() {
	        return isEditFlag;
	    }
	
	    public void setIsEditFlag(int isEditFlag) {
	        this.isEditFlag = isEditFlag;
	    } 
	
	    public String getOrderState() {
	        return orderState;
	    }
	
	    public void setOrderState(String orderState) {
	        this.orderState = orderState;
	    } 
	
	    public int getDiscountAmount() {
	        return discountAmount;
	    }
	
	    public void setDiscountAmount(int discountAmount) {
	        this.discountAmount = discountAmount;
	    } 
	
	    public String getWaterElectronicPaymentPic() {
	        return waterElectronicPaymentPic;
	    }
	
	    public void setWaterElectronicPaymentPic(String waterElectronicPaymentPic) {
	        this.waterElectronicPaymentPic = waterElectronicPaymentPic;
	    } 
	
	    public String getSchool() {
	        return school;
	    }
	
	    public void setSchool(String school) {
	        this.school = school;
	    } 
	
	    public String getExResultInfo() {
	        return exResultInfo;
	    }
	
	    public void setExResultInfo(String exResultInfo) {
	        this.exResultInfo = exResultInfo;
	    } 
	
	    public String getName() {
	        return name;
	    }
	
	    public void setName(String name) {
	        this.name = name;
	    } 
	
	    public String getMaritalStatus() {
	        return maritalStatus;
	    }
	
	    public void setMaritalStatus(String maritalStatus) {
	        this.maritalStatus = maritalStatus;
	    } 
	
	    public String getProvinceName() {
	        return provinceName;
	    }
	
	    public void setProvinceName(String provinceName) {
	        this.provinceName = provinceName;
	    } 
	
	    public String getOrderAuthTypeDesc() {
	        return orderAuthTypeDesc;
	    }
	
	    public void setOrderAuthTypeDesc(String orderAuthTypeDesc) {
	        this.orderAuthTypeDesc = orderAuthTypeDesc;
	    } 
	
	    public boolean getIsShowBuyFlag() {
	        return isShowBuyFlag;
	    }
	
	    public void setIsShowBuyFlag(boolean isShowBuyFlag) {
	        this.isShowBuyFlag = isShowBuyFlag;
	    } 
	
	    public String getInnerFlag() {
	        return innerFlag;
	    }
	
	    public void setInnerFlag(String innerFlag) {
	        this.innerFlag = innerFlag;
	    } 
	
	    public String getPensionDetailPic() {
	        return pensionDetailPic;
	    }
	
	    public void setPensionDetailPic(String pensionDetailPic) {
	        this.pensionDetailPic = pensionDetailPic;
	    } 
	
	    public String getProvince() {
	        return province;
	    }
	
	    public void setProvince(String province) {
	        this.province = province;
	    } 
	
	    public int getNondeliveryFlag() {
	        return nondeliveryFlag;
	    }
	
	    public void setNondeliveryFlag(int nondeliveryFlag) {
	        this.nondeliveryFlag = nondeliveryFlag;
	    } 
	
	    public String getPhoneTimeDesc() {
	        return phoneTimeDesc;
	    }
	
	    public void setPhoneTimeDesc(String phoneTimeDesc) {
	        this.phoneTimeDesc = phoneTimeDesc;
	    } 
	
	    public int getWaitAuthChooseFlag() {
	        return waitAuthChooseFlag;
	    }
	
	    public void setWaitAuthChooseFlag(int waitAuthChooseFlag) {
	        this.waitAuthChooseFlag = waitAuthChooseFlag;
	    } 
	
	    public String getReceiverId() {
	        return receiverId;
	    }
	
	    public void setReceiverId(String receiverId) {
	        this.receiverId = receiverId;
	    } 
	
	    public String getMonRepayDay() {
	        return monRepayDay;
	    }
	
	    public void setMonRepayDay(String monRepayDay) {
	        this.monRepayDay = monRepayDay;
	    } 
	
	    public String getCreateTime() {
	        return createTime;
	    }
	
	    public void setCreateTime(String createTime) {
	        this.createTime = createTime;
	    } 
	
	    public String getExId() {
	        return exId;
	    }
	
	    public void setExId(String exId) {
	        this.exId = exId;
	    } 
	
	    public String getOrderDeliveryName() {
	        return orderDeliveryName;
	    }
	
	    public void setOrderDeliveryName(String orderDeliveryName) {
	        this.orderDeliveryName = orderDeliveryName;
	    } 
	
	    public int getExperienceGoldFlag() {
	        return experienceGoldFlag;
	    }
	
	    public void setExperienceGoldFlag(int experienceGoldFlag) {
	        this.experienceGoldFlag = experienceGoldFlag;
	    } 
	
	    public String getExtInfoJson() {
	        return extInfoJson;
	    }
	
	    public void setExtInfoJson(String extInfoJson) {
	        this.extInfoJson = extInfoJson;
	    } 
	
	    public String getFirstName() {
	        return firstName;
	    }
	
	    public void setFirstName(String firstName) {
	        this.firstName = firstName;
	    } 
	
	    public String getDiscountId() {
	        return discountId;
	    }
	
	    public void setDiscountId(String discountId) {
	        this.discountId = discountId;
	    } 
	
	    public int getCanEvaDelivery() {
	        return canEvaDelivery;
	    }
	
	    public void setCanEvaDelivery(int canEvaDelivery) {
	        this.canEvaDelivery = canEvaDelivery;
	    } 
	
	    public int getTotalMonFee() {
	        return totalMonFee;
	    }
	
	    public void setTotalMonFee(int totalMonFee) {
	        this.totalMonFee = totalMonFee;
	    } 
	
	    public boolean getIsShowPayFlag() {
	        return isShowPayFlag;
	    }
	
	    public void setIsShowPayFlag(boolean isShowPayFlag) {
	        this.isShowPayFlag = isShowPayFlag;
	    } 
	
	    public String getLaborSignaturePic() {
	        return laborSignaturePic;
	    }
	
	    public void setLaborSignaturePic(String laborSignaturePic) {
	        this.laborSignaturePic = laborSignaturePic;
	    } 
	
	    public String getCreditId() {
	        return creditId;
	    }
	
	    public void setCreditId(String creditId) {
	        this.creditId = creditId;
	    } 
	
	    public int getIsCancelFlag() {
	        return isCancelFlag;
	    }
	
	    public void setIsCancelFlag(int isCancelFlag) {
	        this.isCancelFlag = isCancelFlag;
	    } 
	
	    public String getReceiptMobile() {
	        return receiptMobile;
	    }
	
	    public void setReceiptMobile(String receiptMobile) {
	        this.receiptMobile = receiptMobile;
	    } 
	
	    public String getPayType() {
	        return payType;
	    }
	
	    public void setPayType(String payType) {
	        this.payType = payType;
	    } 
	
	    public String getOrderId() {
	        return orderId;
	    }
	
	    public void setOrderId(String orderId) {
	        this.orderId = orderId;
	    } 
	
	    public String getJobProofPic() {
	        return jobProofPic;
	    }
	
	    public void setJobProofPic(String jobProofPic) {
	        this.jobProofPic = jobProofPic;
	    } 
	
	    public String getOrderStateDesc() {
	        return orderStateDesc;
	    }
	
	    public void setOrderStateDesc(String orderStateDesc) {
	        this.orderStateDesc = orderStateDesc;
	    } 
	
	    public String getJdAccountName() {
	        return jdAccountName;
	    }
	
	    public void setJdAccountName(String jdAccountName) {
	        this.jdAccountName = jdAccountName;
	    } 
	
	    public String getEduLevel() {
	        return eduLevel;
	    }
	
	    public void setEduLevel(String eduLevel) {
	        this.eduLevel = eduLevel;
	    } 
	
	    public int getFiftyPercentOffFlag() {
	        return fiftyPercentOffFlag;
	    }
	
	    public void setFiftyPercentOffFlag(int fiftyPercentOffFlag) {
	        this.fiftyPercentOffFlag = fiftyPercentOffFlag;
	    } 
	
	    public String getEmployStatus() {
	        return employStatus;
	    }
	
	    public void setEmployStatus(String employStatus) {
	        this.employStatus = employStatus;
	    } 
	
	    public String getAddress() {
	        return address;
	    }
	
	    public void setAddress(String address) {
	        this.address = address;
	    } 
	
	    public String getDorm() {
	        return dorm;
	    }
	
	    public void setDorm(String dorm) {
	        this.dorm = dorm;
	    } 
	
	    public int getCanCheckFlag() {
	        return canCheckFlag;
	    }
	
	    public void setCanCheckFlag(int canCheckFlag) {
	        this.canCheckFlag = canCheckFlag;
	    } 
	
	    public String getAssistedPic10() {
	        return assistedPic10;
	    }
	
	    public void setAssistedPic10(String assistedPic10) {
	        this.assistedPic10 = assistedPic10;
	    } 
	
	    public String getMaxFqNum() {
	        return maxFqNum;
	    }
	
	    public void setMaxFqNum(String maxFqNum) {
	        this.maxFqNum = maxFqNum;
	    } 
	
	    public String getDeliveryAddress() {
	        return deliveryAddress;
	    }
	
	    public void setDeliveryAddress(String deliveryAddress) {
	        this.deliveryAddress = deliveryAddress;
	    } 
	
	    public int getTotalAmount() {
	        return totalAmount;
	    }
	
	    public void setTotalAmount(int totalAmount) {
	        this.totalAmount = totalAmount;
	    } 
	
	    public int getCommentFlag() {
	        return commentFlag;
	    }
	
	    public void setCommentFlag(int commentFlag) {
	        this.commentFlag = commentFlag;
	    } 
	
	    public String getBankType() {
	        return bankType;
	    }
	
	    public void setBankType(String bankType) {
	        this.bankType = bankType;
	    } 
	
	    public int getUrgeOrderFlag() {
	        return urgeOrderFlag;
	    }
	
	    public void setUrgeOrderFlag(int urgeOrderFlag) {
	        this.urgeOrderFlag = urgeOrderFlag;
	    } 
	
	    public String getModifyTime() {
	        return modifyTime;
	    }
	
	    public void setModifyTime(String modifyTime) {
	        this.modifyTime = modifyTime;
	    } 
	
	    public int getCanSubmitFlag() {
	        return canSubmitFlag;
	    }
	
	    public void setCanSubmitFlag(int canSubmitFlag) {
	        this.canSubmitFlag = canSubmitFlag;
	    } 
	
	    public String getRepayNum() {
	        return repayNum;
	    }
	
	    public void setRepayNum(String repayNum) {
	        this.repayNum = repayNum;
	    } 
	
	    public String getSubFactoryId() {
	        return subFactoryId;
	    }
	
	    public void setSubFactoryId(String subFactoryId) {
	        this.subFactoryId = subFactoryId;
	    } 
	
	    public int getPayFirstpayFlag() {
	        return payFirstpayFlag;
	    }
	
	    public void setPayFirstpayFlag(int payFirstpayFlag) {
	        this.payFirstpayFlag = payFirstpayFlag;
	    } 
	
	    public int getConsumeFlag() {
	        return consumeFlag;
	    }
	
	    public void setConsumeFlag(int consumeFlag) {
	        this.consumeFlag = consumeFlag;
	    } 
	
	    public String getCounty() {
	        return county;
	    }
	
	    public void setCounty(String county) {
	        this.county = county;
	    } 
	
	    public int getOrderOutReturn() {
	        return orderOutReturn;
	    }
	
	    public void setOrderOutReturn(int orderOutReturn) {
	        this.orderOutReturn = orderOutReturn;
	    } 
	
	    public String getNextRepayDay() {
	        return nextRepayDay;
	    }
	
	    public void setNextRepayDay(String nextRepayDay) {
	        this.nextRepayDay = nextRepayDay;
	    } 
	
	    public int getCheckSubmitFlag() {
	        return checkSubmitFlag;
	    }
	
	    public void setCheckSubmitFlag(int checkSubmitFlag) {
	        this.checkSubmitFlag = checkSubmitFlag;
	    } 
	
	    public int getStaffFlag() {
	        return staffFlag;
	    }
	
	    public void setStaffFlag(int staffFlag) {
	        this.staffFlag = staffFlag;
	    } 
	
	    public String getArea() {
	        return area;
	    }
	
	    public void setArea(String area) {
	        this.area = area;
	    } 
	
	    public int getTotalManageFee() {
	        return totalManageFee;
	    }
	
	    public void setTotalManageFee(int totalManageFee) {
	        this.totalManageFee = totalManageFee;
	    } 
	
	    public int getRepayListShowFlag() {
	        return repayListShowFlag;
	    }
	
	    public void setRepayListShowFlag(int repayListShowFlag) {
	        this.repayListShowFlag = repayListShowFlag;
	    } 
	
	    public String getBadgePic() {
	        return badgePic;
	    }
	
	    public void setBadgePic(String badgePic) {
	        this.badgePic = badgePic;
	    } 
	
	    public int getOrderAuthType() {
	        return orderAuthType;
	    }
	
	    public void setOrderAuthType(int orderAuthType) {
	        this.orderAuthType = orderAuthType;
	    } 
	
	    public String getMaritalStatusDesc() {
	        return maritalStatusDesc;
	    }
	
	    public void setMaritalStatusDesc(String maritalStatusDesc) {
	        this.maritalStatusDesc = maritalStatusDesc;
	    } 
	
	    public String getSchoolId() {
	        return schoolId;
	    }
	
	    public void setSchoolId(String schoolId) {
	        this.schoolId = schoolId;
	    } 
	
	    public String getReceiptMobileEcp() {
	        return receiptMobileEcp;
	    }
	
	    public void setReceiptMobileEcp(String receiptMobileEcp) {
	        this.receiptMobileEcp = receiptMobileEcp;
	    } 
	
	    public String getCreditLineType() {
	        return creditLineType;
	    }
	
	    public void setCreditLineType(String creditLineType) {
	        this.creditLineType = creditLineType;
	    } 
	
	    public String getSaleType() {
	        return saleType;
	    }
	
	    public void setSaleType(String saleType) {
	        this.saleType = saleType;
	    } 
	
	    public int getReceiveType() {
	        return receiveType;
	    }
	
	    public void setReceiveType(int receiveType) {
	        this.receiveType = receiveType;
	    } 
	
	    public String getUserType() {
	        return userType;
	    }
	
	    public void setUserType(String userType) {
	        this.userType = userType;
	    } 
	
	    public String getDelivery() {
	        return delivery;
	    }
	
	    public void setDelivery(String delivery) {
	        this.delivery = delivery;
	    } 
	
	    public String getReceiveTypeDesc() {
	        return receiveTypeDesc;
	    }
	
	    public void setReceiveTypeDesc(String receiveTypeDesc) {
	        this.receiveTypeDesc = receiveTypeDesc;
	    } 
	
	    public int getTotalFirstpay() {
	        return totalFirstpay;
	    }
	
	    public void setTotalFirstpay(int totalFirstpay) {
	        this.totalFirstpay = totalFirstpay;
	    } 
	
	    public String getProvinceId() {
	        return provinceId;
	    }
	
	    public void setProvinceId(String provinceId) {
	        this.provinceId = provinceId;
	    } 
	
	    public String getCreditIdEcp() {
	        return creditIdEcp;
	    }
	
	    public void setCreditIdEcp(String creditIdEcp) {
	        this.creditIdEcp = creditIdEcp;
	    } 
	
	    public int getFinishTradeFlag() {
	        return finishTradeFlag;
	    }
	
	    public void setFinishTradeFlag(int finishTradeFlag) {
	        this.finishTradeFlag = finishTradeFlag;
	    } 
	
	    public int getReduceAmount() {
	        return reduceAmount;
	    }
	
	    public void setReduceAmount(int reduceAmount) {
	        this.reduceAmount = reduceAmount;
	    } 
	
	    public int getOrderStateEx() {
	        return orderStateEx;
	    }
	
	    public void setOrderStateEx(int orderStateEx) {
	        this.orderStateEx = orderStateEx;
	    } 
	
	    public String getScenePic() {
	        return scenePic;
	    }
	
	    public void setScenePic(String scenePic) {
	        this.scenePic = scenePic;
	    } 
	
	    public String getUid() {
	        return uid;
	    }
	
	    public void setUid(String uid) {
	        this.uid = uid;
	    } 
	
	    public int getRebutFlag() {
	        return rebutFlag;
	    }
	
	    public void setRebutFlag(int rebutFlag) {
	        this.rebutFlag = rebutFlag;
	    } 
	
	    public int getExState() {
	        return exState;
	    }
	
	    public void setExState(int exState) {
	        this.exState = exState;
	    } 
	
	    public String getRepayType() {
	        return repayType;
	    }
	
	    public void setRepayType(String repayType) {
	        this.repayType = repayType;
	    } 
	
	    public int getExperienceGold() {
	        return experienceGold;
	    }
	
	    public void setExperienceGold(int experienceGold) {
	        this.experienceGold = experienceGold;
	    } 
	
	    public String getFactoryName() {
	        return factoryName;
	    }
	
	    public void setFactoryName(String factoryName) {
	        this.factoryName = factoryName;
	    } 
	
	    public String getSubFactoryName() {
	        return subFactoryName;
	    }
	
	    public void setSubFactoryName(String subFactoryName) {
	        this.subFactoryName = subFactoryName;
	    } 
	
	    public String getMonthlySalary() {
	        return monthlySalary;
	    }
	
	    public void setMonthlySalary(String monthlySalary) {
	        this.monthlySalary = monthlySalary;
	    } 
	
	    public String getCountyId() {
	        return countyId;
	    }
	
	    public void setCountyId(String countyId) {
	        this.countyId = countyId;
	    } 
	
	    public String getSaleTypeDesc() {
	        return saleTypeDesc;
	    }
	
	    public void setSaleTypeDesc(String saleTypeDesc) {
	        this.saleTypeDesc = saleTypeDesc;
	    } 
	
	    public String getAccountDate() {
	        return accountDate;
	    }
	
	    public void setAccountDate(String accountDate) {
	        this.accountDate = accountDate;
	    } 
	
	    public String getOrderType() {
	        return orderType;
	    }
	
	    public void setOrderType(String orderType) {
	        this.orderType = orderType;
	    } 
	
	    public String getIncomePayrollPic1() {
	        return incomePayrollPic1;
	    }
	
	    public void setIncomePayrollPic1(String incomePayrollPic1) {
	        this.incomePayrollPic1 = incomePayrollPic1;
	    } 
	
	    public String getPayStateDesc() {
	        return payStateDesc;
	    }
	
	    public void setPayStateDesc(String payStateDesc) {
	        this.payStateDesc = payStateDesc;
	    } 
	
	    public String getCreditFront() {
	        return creditFront;
	    }
	
	    public void setCreditFront(String creditFront) {
	        this.creditFront = creditFront;
	    } 
	
	    public int getInAfterSale() {
	        return inAfterSale;
	    }
	
	    public void setInAfterSale(int inAfterSale) {
	        this.inAfterSale = inAfterSale;
	    } 
	
	    public String getEduLevelDesc() {
	        return eduLevelDesc;
	    }
	
	    public void setEduLevelDesc(String eduLevelDesc) {
	        this.eduLevelDesc = eduLevelDesc;
	    } 
	
	    public String getDepartment() {
	        return department;
	    }
	
	    public void setDepartment(String department) {
	        this.department = department;
	    } 
	
	    public String getPositionDesc() {
	        return positionDesc;
	    }
	
	    public void setPositionDesc(String positionDesc) {
	        this.positionDesc = positionDesc;
	    } 
	
	    public String getPayState() {
	        return payState;
	    }
	
	    public void setPayState(String payState) {
	        this.payState = payState;
	    } 
	
	    public String getCheckResult() {
	        return checkResult;
	    }
	
	    public void setCheckResult(String checkResult) {
	        this.checkResult = checkResult;
	    } 
	
	    public String getDeliveryMobile() {
	        return deliveryMobile;
	    }
	
	    public void setDeliveryMobile(String deliveryMobile) {
	        this.deliveryMobile = deliveryMobile;
	    } 
	
	    public String getFactoryTel() {
	        return factoryTel;
	    }
	
	    public void setFactoryTel(String factoryTel) {
	        this.factoryTel = factoryTel;
	    } 
	
	    public int getTestFlag() {
	        return testFlag;
	    }
	
	    public void setTestFlag(int testFlag) {
	        this.testFlag = testFlag;
	    } 
	
	    public String getUserSubtype() {
	        return userSubtype;
	    }
	
	    public void setUserSubtype(String userSubtype) {
	        this.userSubtype = userSubtype;
	    } 
	
	    public int getIsDrawFailedFlag() {
	        return isDrawFailedFlag;
	    }
	
	    public void setIsDrawFailedFlag(int isDrawFailedFlag) {
	        this.isDrawFailedFlag = isDrawFailedFlag;
	    } 
	
	    public String getCityName() {
	        return cityName;
	    }
	
	    public void setCityName(String cityName) {
	        this.cityName = cityName;
	    } 
	
	    public int getOrderOutEx() {
	        return orderOutEx;
	    }
	
	    public void setOrderOutEx(int orderOutEx) {
	        this.orderOutEx = orderOutEx;
	    } 
	
	    public String getIncomePayrollPic2() {
	        return incomePayrollPic2;
	    }
	
	    public void setIncomePayrollPic2(String incomePayrollPic2) {
	        this.incomePayrollPic2 = incomePayrollPic2;
	    } 
	
	    public String getSocialSecurityDetailPic() {
	        return socialSecurityDetailPic;
	    }
	
	    public void setSocialSecurityDetailPic(String socialSecurityDetailPic) {
	        this.socialSecurityDetailPic = socialSecurityDetailPic;
	    } 
	
	    public int getTotalCapital() {
	        return totalCapital;
	    }
	
	    public void setTotalCapital(int totalCapital) {
	        this.totalCapital = totalCapital;
	    } 
	
	    public int getSelfValidateFlag() {
	        return selfValidateFlag;
	    }
	
	    public void setSelfValidateFlag(int selfValidateFlag) {
	        this.selfValidateFlag = selfValidateFlag;
	    } 
	
	    public String getArriveTime() {
	        return arriveTime;
	    }
	
	    public void setArriveTime(String arriveTime) {
	        this.arriveTime = arriveTime;
	    } 
	
	    public int getTotalHandlingFee() {
	        return totalHandlingFee;
	    }
	
	    public void setTotalHandlingFee(int totalHandlingFee) {
	        this.totalHandlingFee = totalHandlingFee;
	    } 
	
	    public int getOrderExCancelFlag() {
	        return orderExCancelFlag;
	    }
	
	    public void setOrderExCancelFlag(int orderExCancelFlag) {
	        this.orderExCancelFlag = orderExCancelFlag;
	    } 
	
	    public String getPosition() {
	        return position;
	    }
	
	    public void setPosition(String position) {
	        this.position = position;
	    } 
	
		public static class OrderInfo {
			private String productInfo; 
			private List<String> skuPic; 
			private String skuId; 
			private String quantity; 
		
			public static OrderInfo objectFromJSON(JSONObject jsonObject) {
			    OrderInfo object = new OrderInfo();
			
				object.productInfo = jsonObject.optString("product_info");
				if (jsonObject.optJSONArray("sku_pic") != null) {
				    JSONArray jsonArray = jsonObject.optJSONArray("sku_pic");
				    List<String> list = new ArrayList<>();
				    for (int i = 0; i < jsonArray.length(); i++) {
						String item = jsonArray.optString(i);
						list.add(item);
				    }
				    object.skuPic = list;
				}
				
				object.skuId = jsonObject.optString("sku_id");
				object.quantity = jsonObject.optString("quantity");
				return object;
			}
			
			public static JSONObject JSONFromObject(OrderInfo object) {
			    JSONObject jsonObject = new JSONObject();
			    try { 
					jsonObject.put("product_info", object.productInfo);
					if(object.skuPic!=null){
					    List<String> list = object.skuPic;
					    JSONArray jsonArray = new JSONArray();
						for (String item : list) {
						    jsonArray.put(item);
						} 
					    jsonObject.put("sku_pic",jsonArray);
					} 
					jsonObject.put("sku_id", object.skuId);
					jsonObject.put("quantity", object.quantity);
				} catch (JSONException e) {
				    e.printStackTrace();
				}
				
				return jsonObject; 
			}
		
		    public String getProductInfo() {
		        return productInfo;
		    }
		
		    public void setProductInfo(String productInfo) {
		        this.productInfo = productInfo;
		    } 
		
		    public List<String> getSkuPic() {
		        return skuPic;
		    }
		
		    public void setSkuPic(List<String> skuPic) {
		        this.skuPic = skuPic;
		    } 
		
		    public String getSkuId() {
		        return skuId;
		    }
		
		    public void setSkuId(String skuId) {
		        this.skuId = skuId;
		    } 
		
		    public String getQuantity() {
		        return quantity;
		    }
		
		    public void setQuantity(String quantity) {
		        this.quantity = quantity;
		    } 
		}
		
	}
	
}

