// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 14:56:33,  DO NOT EDIT!

#import <Foundation/Foundation.h>

@class MJTestModel_CreditLine;
@class MJTestModel_MyContent;
@class MJTestModel_PocketOrderInfo;
@class MJTestModel_PocketOrderInfo_OrderInfo;

@interface MJTestModel : NSObject 
@property (nonatomic, retain) NSString* le_res_info;
@property (nonatomic, retain) MJTestModel_CreditLine*  le_credit_line;
@property (nonatomic, assign) int le_user_card_auth_verify_flag;
@property (nonatomic, retain) NSMutableArray<MJTestModel_MyContent*>*  le_my_content;
@property (nonatomic, retain) NSString* le_credit_url;
@property (nonatomic, assign) int le_credit_improve_status;
@property (nonatomic, assign) int le_result;
@property (nonatomic, assign) int le_pocket_status;
@property (nonatomic, assign) int le_is_login;
@property (nonatomic, retain) NSMutableArray<MJTestModel_PocketOrderInfo*>*  le_pocket_order_info;
@end


@interface MJTestModel_CreditLine : NSObject 
@property (nonatomic, retain) NSString* le_pocket_available_credit;
@property (nonatomic, retain) NSString* le_predict_goods_avl_credit;
@property (nonatomic, retain) NSString* le_predict_pocket_avl_credit;
@property (nonatomic, retain) NSString* le_res_info;
@property (nonatomic, retain) NSString* le_credit_line;
@property (nonatomic, retain) NSString* le_predict_lack_credit;
@property (nonatomic, retain) NSString* le_good_credit;
@property (nonatomic, retain) NSString* le_goods_lack_credit;
@property (nonatomic, retain) NSString* le_predict_pocket_lack_credit;
@property (nonatomic, retain) NSString* le_predict_goods_lack_credit;
@property (nonatomic, retain) NSString* le_pocket_credit;
@property (nonatomic, retain) NSString* le_goods_available_credit;
@property (nonatomic, retain) NSString* le_lack_credit;
@property (nonatomic, retain) NSString* le_pocket_lack_credit;
@property (nonatomic, retain) NSString* le_available_credit_line;
@property (nonatomic, retain) NSString* le_predict_avl_credit;
@property (nonatomic, retain) NSString* le_predict_credit;
@property (nonatomic, retain) NSString* le_temp_max_credit;
@property (nonatomic, retain) NSString* le_predict_pocket_credit;
@property (nonatomic, retain) NSString* le_predict_goods_credit;
@property (nonatomic, retain) NSString* le_result;
@end


@interface MJTestModel_MyContent : NSObject 
@property (nonatomic, retain) NSString* le_can_app_show;
@property (nonatomic, retain) NSString* le_need_red_dot;
@property (nonatomic, retain) NSString* le_title;
@property (nonatomic, retain) NSString* le_url;
@property (nonatomic, retain) NSString* le_tip_img_url;
@property (nonatomic, retain) NSString* le_tip_text;
@property (nonatomic, retain) NSString* le_tip_visible;
@property (nonatomic, retain) NSString* le_config_key;
@property (nonatomic, retain) NSString* le_key;
@property (nonatomic, retain) NSString* le_h5_enabled;
@property (nonatomic, retain) NSString* le_img_url;
@property (nonatomic, retain) NSString* le_can_h5_show;
@end


@interface MJTestModel_PocketOrderInfo : NSObject 
@property (nonatomic, retain) NSString* le_assisted_pic_4;
@property (nonatomic, retain) NSString* le_assisted_pic_5;
@property (nonatomic, retain) NSString* le_area_id;
@property (nonatomic, retain) NSString* le_assisted_pic_7;
@property (nonatomic, retain) NSString* le_assisted_pic_1;
@property (nonatomic, retain) NSString* le_assisted_pic_2;
@property (nonatomic, retain) NSString* le_assisted_pic_3;
@property (nonatomic, retain) NSString* le_city_id;
@property (nonatomic, retain) NSString* le_labor_home_pic;
@property (nonatomic, retain) NSString* le_assisted_pic_8;
@property (nonatomic, retain) NSString* le_assisted_pic_6;
@property (nonatomic, retain) NSString* le_order_delivery_mobile;
@property (nonatomic, assign) int le_is_close_flag;
@property (nonatomic, retain) NSString* le_factory_id;
@property (nonatomic, assign) int le_order_ex_return_flag;
@property (nonatomic, retain) NSString* le_credit_back;
@property (nonatomic, assign) int le_total_mon_pay;
@property (nonatomic, retain) NSString* le_phone_time;
@property (nonatomic, assign) int le_submit_close_flag;
@property (nonatomic, assign) int le_order_finish_flag;
@property (nonatomic, assign) int le_order_ex_express_flag;
@property (nonatomic, assign) int le_order_ex_finish_flag;
@property (nonatomic, retain) NSString* le_city;
@property (nonatomic, retain) NSString* le_entry_time;
@property (nonatomic, assign) int le_can_eva_sku;
@property (nonatomic, assign) int le_hide_flag;
@property (nonatomic, retain) NSMutableArray<MJTestModel_PocketOrderInfo_OrderInfo*>*  le_order_info;
@property (nonatomic, retain) NSString* le_assisted_pic_9;
@property (nonatomic, assign) int le_is_edit_flag;
@property (nonatomic, retain) NSString* le_order_state;
@property (nonatomic, assign) int le_discount_amount;
@property (nonatomic, retain) NSString* le_water_electronic_payment_pic;
@property (nonatomic, retain) NSString* le_school;
@property (nonatomic, retain) NSString* le_ex_result_info;
@property (nonatomic, retain) NSString* le_name;
@property (nonatomic, retain) NSString* le_marital_status;
@property (nonatomic, retain) NSString* le_province_name;
@property (nonatomic, retain) NSString* le_order_auth_type_desc;
@property (nonatomic, assign) BOOL le_is_show_buy_flag;
@property (nonatomic, retain) NSString* le_inner_flag;
@property (nonatomic, retain) NSString* le_pension_detail_pic;
@property (nonatomic, retain) NSString* le_province;
@property (nonatomic, assign) int le_nondelivery_flag;
@property (nonatomic, retain) NSString* le_phone_time_desc;
@property (nonatomic, assign) int le_wait_auth_choose_flag;
@property (nonatomic, retain) NSString* le_receiver_id;
@property (nonatomic, retain) NSString* le_mon_repay_day;
@property (nonatomic, retain) NSString* le_create_time;
@property (nonatomic, retain) NSString* le_ex_id;
@property (nonatomic, retain) NSString* le_order_delivery_name;
@property (nonatomic, assign) int le_experience_gold_flag;
@property (nonatomic, retain) NSString* le_ext_info_json;
@property (nonatomic, retain) NSString* le_first_name;
@property (nonatomic, retain) NSString* le_discount_id;
@property (nonatomic, assign) int le_can_eva_delivery;
@property (nonatomic, assign) int le_total_mon_fee;
@property (nonatomic, assign) BOOL le_is_show_pay_flag;
@property (nonatomic, retain) NSString* le_labor_signature_pic;
@property (nonatomic, retain) NSString* le_credit_id;
@property (nonatomic, assign) int le_is_cancel_flag;
@property (nonatomic, retain) NSString* le_receipt_mobile;
@property (nonatomic, retain) NSString* le_pay_type;
@property (nonatomic, retain) NSString* le_order_id;
@property (nonatomic, retain) NSString* le_job_proof_pic;
@property (nonatomic, retain) NSString* le_order_state_desc;
@property (nonatomic, retain) NSString* le_jd_account_name;
@property (nonatomic, retain) NSString* le_edu_level;
@property (nonatomic, assign) int le_fifty_percent_off_flag;
@property (nonatomic, retain) NSString* le_employ_status;
@property (nonatomic, retain) NSString* le_address;
@property (nonatomic, retain) NSString* le_dorm;
@property (nonatomic, assign) int le_can_check_flag;
@property (nonatomic, retain) NSString* le_assisted_pic_10;
@property (nonatomic, retain) NSString* le_max_fq_num;
@property (nonatomic, retain) NSString* le_delivery_address;
@property (nonatomic, assign) int le_total_amount;
@property (nonatomic, assign) int le_comment_flag;
@property (nonatomic, retain) NSString* le_bank_type;
@property (nonatomic, assign) int le_urge_order_flag;
@property (nonatomic, retain) NSString* le_modify_time;
@property (nonatomic, assign) int le_can_submit_flag;
@property (nonatomic, retain) NSString* le_repay_num;
@property (nonatomic, retain) NSString* le_sub_factory_id;
@property (nonatomic, assign) int le_pay_firstpay_flag;
@property (nonatomic, assign) int le_consume_flag;
@property (nonatomic, retain) NSString* le_county;
@property (nonatomic, assign) int le_order_out_return;
@property (nonatomic, retain) NSString* le_next_repay_day;
@property (nonatomic, assign) int le_check_submit_flag;
@property (nonatomic, assign) int le_staff_flag;
@property (nonatomic, retain) NSString* le_area;
@property (nonatomic, assign) int le_total_manage_fee;
@property (nonatomic, assign) int le_repay_list_show_flag;
@property (nonatomic, retain) NSString* le_badge_pic;
@property (nonatomic, assign) int le_order_auth_type;
@property (nonatomic, retain) NSString* le_marital_status_desc;
@property (nonatomic, retain) NSString* le_school_id;
@property (nonatomic, retain) NSString* le_receipt_mobile_ecp;
@property (nonatomic, retain) NSString* le_credit_line_type;
@property (nonatomic, retain) NSString* le_sale_type;
@property (nonatomic, assign) int le_receive_type;
@property (nonatomic, retain) NSString* le_user_type;
@property (nonatomic, retain) NSString* le_delivery;
@property (nonatomic, retain) NSString* le_receive_type_desc;
@property (nonatomic, assign) int le_total_firstpay;
@property (nonatomic, retain) NSString* le_province_id;
@property (nonatomic, retain) NSString* le_credit_id_ecp;
@property (nonatomic, assign) int le_finish_trade_flag;
@property (nonatomic, assign) int le_reduce_amount;
@property (nonatomic, assign) int le_order_state_ex;
@property (nonatomic, retain) NSString* le_scene_pic;
@property (nonatomic, retain) NSString* le_uid;
@property (nonatomic, assign) int le_rebut_flag;
@property (nonatomic, assign) int le_ex_state;
@property (nonatomic, retain) NSString* le_repay_type;
@property (nonatomic, assign) int le_experience_gold;
@property (nonatomic, retain) NSString* le_factory_name;
@property (nonatomic, retain) NSString* le_sub_factory_name;
@property (nonatomic, retain) NSString* le_monthly_salary;
@property (nonatomic, retain) NSString* le_county_id;
@property (nonatomic, retain) NSString* le_sale_type_desc;
@property (nonatomic, retain) NSString* le_account_date;
@property (nonatomic, retain) NSString* le_order_type;
@property (nonatomic, retain) NSString* le_income_payroll_pic_1;
@property (nonatomic, retain) NSString* le_pay_state_desc;
@property (nonatomic, retain) NSString* le_credit_front;
@property (nonatomic, assign) int le_in_after_sale;
@property (nonatomic, retain) NSString* le_edu_level_desc;
@property (nonatomic, retain) NSString* le_department;
@property (nonatomic, retain) NSString* le_position_desc;
@property (nonatomic, retain) NSString* le_pay_state;
@property (nonatomic, retain) NSString* le_check_result;
@property (nonatomic, retain) NSString* le_delivery_mobile;
@property (nonatomic, retain) NSString* le_factory_tel;
@property (nonatomic, assign) int le_test_flag;
@property (nonatomic, retain) NSString* le_user_subtype;
@property (nonatomic, assign) int le_is_draw_failed_flag;
@property (nonatomic, retain) NSString* le_city_name;
@property (nonatomic, assign) int le_order_out_ex;
@property (nonatomic, retain) NSString* le_income_payroll_pic_2;
@property (nonatomic, retain) NSString* le_social_security_detail_pic;
@property (nonatomic, assign) int le_total_capital;
@property (nonatomic, assign) int le_self_validate_flag;
@property (nonatomic, retain) NSString* le_arrive_time;
@property (nonatomic, assign) int le_total_handling_fee;
@property (nonatomic, assign) int le_order_ex_cancel_flag;
@property (nonatomic, retain) NSString* le_position;
@end


@interface MJTestModel_PocketOrderInfo_OrderInfo : NSObject 
@property (nonatomic, retain) NSString* le_product_info;
@property (nonatomic, retain) NSMutableArray<NSString*>*  le_sku_pic;
@property (nonatomic, retain) NSString* le_sku_id;
@property (nonatomic, retain) NSString* le_quantity;
@end


