// Generated by the LeJson.py,  DO NOT EDIT!
// Feedback to iwanglian@github.com,  DO NOT EDIT!

// Created by alick on 2016-05-23 13:28:25,  DO NOT EDIT!

#import "MJTestModel.h"

@implementation MJTestModel


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_a" : @"a",
        @"le_b" : @"b",

    };
}
@end


