// Generated by the LeJson.py,  DO NOT EDIT!
// Feedback to iwanglian@github.com,  DO NOT EDIT!

// Created by alick on 2016-05-23 13:28:25,  DO NOT EDIT!

#import <Foundation/Foundation.h>


@interface MJTestModel : NSObject 
@property (nonatomic, assign) int le_a;
@property (nonatomic, retain) NSString* le_b;
@end


