// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 14:56:33,  DO NOT EDIT!

#import "MJTestModel.h"

@implementation MJTestModel


-(instancetype)init{
    self = [super init];
    if (self) {
        self.le_credit_line= [[MJTestModel_CreditLine alloc] init];
        self.le_my_content = [[NSMutableArray alloc] init];
        self.le_pocket_order_info = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{
        @"le_my_content" : @"MJTestModel_MyContent",
        @"le_pocket_order_info" : @"MJTestModel_PocketOrderInfo",

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_res_info" : @"res_info",
        @"le_credit_line" : @"credit_line",
        @"le_user_card_auth_verify_flag" : @"user_card_auth_verify_flag",
        @"le_my_content" : @"my_content",
        @"le_credit_url" : @"credit_url",
        @"le_credit_improve_status" : @"credit_improve_status",
        @"le_result" : @"result",
        @"le_pocket_status" : @"pocket_status",
        @"le_is_login" : @"is_login",
        @"le_pocket_order_info" : @"pocket_order_info",

    };
}
@end


@implementation MJTestModel_CreditLine


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_pocket_available_credit" : @"pocket_available_credit",
        @"le_predict_goods_avl_credit" : @"predict_goods_avl_credit",
        @"le_predict_pocket_avl_credit" : @"predict_pocket_avl_credit",
        @"le_res_info" : @"res_info",
        @"le_credit_line" : @"credit_line",
        @"le_predict_lack_credit" : @"predict_lack_credit",
        @"le_good_credit" : @"good_credit",
        @"le_goods_lack_credit" : @"goods_lack_credit",
        @"le_predict_pocket_lack_credit" : @"predict_pocket_lack_credit",
        @"le_predict_goods_lack_credit" : @"predict_goods_lack_credit",
        @"le_pocket_credit" : @"pocket_credit",
        @"le_goods_available_credit" : @"goods_available_credit",
        @"le_lack_credit" : @"lack_credit",
        @"le_pocket_lack_credit" : @"pocket_lack_credit",
        @"le_available_credit_line" : @"available_credit_line",
        @"le_predict_avl_credit" : @"predict_avl_credit",
        @"le_predict_credit" : @"predict_credit",
        @"le_temp_max_credit" : @"temp_max_credit",
        @"le_predict_pocket_credit" : @"predict_pocket_credit",
        @"le_predict_goods_credit" : @"predict_goods_credit",
        @"le_result" : @"result",

    };
}
@end


@implementation MJTestModel_MyContent


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_can_app_show" : @"can_app_show",
        @"le_need_red_dot" : @"need_red_dot",
        @"le_title" : @"title",
        @"le_url" : @"url",
        @"le_tip_img_url" : @"tip_img_url",
        @"le_tip_text" : @"tip_text",
        @"le_tip_visible" : @"tip_visible",
        @"le_config_key" : @"config_key",
        @"le_key" : @"key",
        @"le_h5_enabled" : @"h5_enabled",
        @"le_img_url" : @"img_url",
        @"le_can_h5_show" : @"can_h5_show",

    };
}
@end


@implementation MJTestModel_PocketOrderInfo


-(instancetype)init{
    self = [super init];
    if (self) {
        self.le_order_info = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{
        @"le_order_info" : @"MJTestModel_PocketOrderInfo_OrderInfo",

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_assisted_pic_4" : @"assisted_pic_4",
        @"le_assisted_pic_5" : @"assisted_pic_5",
        @"le_area_id" : @"area_id",
        @"le_assisted_pic_7" : @"assisted_pic_7",
        @"le_assisted_pic_1" : @"assisted_pic_1",
        @"le_assisted_pic_2" : @"assisted_pic_2",
        @"le_assisted_pic_3" : @"assisted_pic_3",
        @"le_city_id" : @"city_id",
        @"le_labor_home_pic" : @"labor_home_pic",
        @"le_assisted_pic_8" : @"assisted_pic_8",
        @"le_assisted_pic_6" : @"assisted_pic_6",
        @"le_order_delivery_mobile" : @"order_delivery_mobile",
        @"le_is_close_flag" : @"is_close_flag",
        @"le_factory_id" : @"factory_id",
        @"le_order_ex_return_flag" : @"order_ex_return_flag",
        @"le_credit_back" : @"credit_back",
        @"le_total_mon_pay" : @"total_mon_pay",
        @"le_phone_time" : @"phone_time",
        @"le_submit_close_flag" : @"submit_close_flag",
        @"le_order_finish_flag" : @"order_finish_flag",
        @"le_order_ex_express_flag" : @"order_ex_express_flag",
        @"le_order_ex_finish_flag" : @"order_ex_finish_flag",
        @"le_city" : @"city",
        @"le_entry_time" : @"entry_time",
        @"le_can_eva_sku" : @"can_eva_sku",
        @"le_hide_flag" : @"hide_flag",
        @"le_order_info" : @"order_info",
        @"le_assisted_pic_9" : @"assisted_pic_9",
        @"le_is_edit_flag" : @"is_edit_flag",
        @"le_order_state" : @"order_state",
        @"le_discount_amount" : @"discount_amount",
        @"le_water_electronic_payment_pic" : @"water_electronic_payment_pic",
        @"le_school" : @"school",
        @"le_ex_result_info" : @"ex_result_info",
        @"le_name" : @"name",
        @"le_marital_status" : @"marital_status",
        @"le_province_name" : @"province_name",
        @"le_order_auth_type_desc" : @"order_auth_type_desc",
        @"le_is_show_buy_flag" : @"is_show_buy_flag",
        @"le_inner_flag" : @"inner_flag",
        @"le_pension_detail_pic" : @"pension_detail_pic",
        @"le_province" : @"province",
        @"le_nondelivery_flag" : @"nondelivery_flag",
        @"le_phone_time_desc" : @"phone_time_desc",
        @"le_wait_auth_choose_flag" : @"wait_auth_choose_flag",
        @"le_receiver_id" : @"receiver_id",
        @"le_mon_repay_day" : @"mon_repay_day",
        @"le_create_time" : @"create_time",
        @"le_ex_id" : @"ex_id",
        @"le_order_delivery_name" : @"order_delivery_name",
        @"le_experience_gold_flag" : @"experience_gold_flag",
        @"le_ext_info_json" : @"ext_info_json",
        @"le_first_name" : @"first_name",
        @"le_discount_id" : @"discount_id",
        @"le_can_eva_delivery" : @"can_eva_delivery",
        @"le_total_mon_fee" : @"total_mon_fee",
        @"le_is_show_pay_flag" : @"is_show_pay_flag",
        @"le_labor_signature_pic" : @"labor_signature_pic",
        @"le_credit_id" : @"credit_id",
        @"le_is_cancel_flag" : @"is_cancel_flag",
        @"le_receipt_mobile" : @"receipt_mobile",
        @"le_pay_type" : @"pay_type",
        @"le_order_id" : @"order_id",
        @"le_job_proof_pic" : @"job_proof_pic",
        @"le_order_state_desc" : @"order_state_desc",
        @"le_jd_account_name" : @"jd_account_name",
        @"le_edu_level" : @"edu_level",
        @"le_fifty_percent_off_flag" : @"fifty_percent_off_flag",
        @"le_employ_status" : @"employ_status",
        @"le_address" : @"address",
        @"le_dorm" : @"dorm",
        @"le_can_check_flag" : @"can_check_flag",
        @"le_assisted_pic_10" : @"assisted_pic_10",
        @"le_max_fq_num" : @"max_fq_num",
        @"le_delivery_address" : @"delivery_address",
        @"le_total_amount" : @"total_amount",
        @"le_comment_flag" : @"comment_flag",
        @"le_bank_type" : @"bank_type",
        @"le_urge_order_flag" : @"urge_order_flag",
        @"le_modify_time" : @"modify_time",
        @"le_can_submit_flag" : @"can_submit_flag",
        @"le_repay_num" : @"repay_num",
        @"le_sub_factory_id" : @"sub_factory_id",
        @"le_pay_firstpay_flag" : @"pay_firstpay_flag",
        @"le_consume_flag" : @"consume_flag",
        @"le_county" : @"county",
        @"le_order_out_return" : @"order_out_return",
        @"le_next_repay_day" : @"next_repay_day",
        @"le_check_submit_flag" : @"check_submit_flag",
        @"le_staff_flag" : @"staff_flag",
        @"le_area" : @"area",
        @"le_total_manage_fee" : @"total_manage_fee",
        @"le_repay_list_show_flag" : @"repay_list_show_flag",
        @"le_badge_pic" : @"badge_pic",
        @"le_order_auth_type" : @"order_auth_type",
        @"le_marital_status_desc" : @"marital_status_desc",
        @"le_school_id" : @"school_id",
        @"le_receipt_mobile_ecp" : @"receipt_mobile_ecp",
        @"le_credit_line_type" : @"credit_line_type",
        @"le_sale_type" : @"sale_type",
        @"le_receive_type" : @"receive_type",
        @"le_user_type" : @"user_type",
        @"le_delivery" : @"delivery",
        @"le_receive_type_desc" : @"receive_type_desc",
        @"le_total_firstpay" : @"total_firstpay",
        @"le_province_id" : @"province_id",
        @"le_credit_id_ecp" : @"credit_id_ecp",
        @"le_finish_trade_flag" : @"finish_trade_flag",
        @"le_reduce_amount" : @"reduce_amount",
        @"le_order_state_ex" : @"order_state_ex",
        @"le_scene_pic" : @"scene_pic",
        @"le_uid" : @"uid",
        @"le_rebut_flag" : @"rebut_flag",
        @"le_ex_state" : @"ex_state",
        @"le_repay_type" : @"repay_type",
        @"le_experience_gold" : @"experience_gold",
        @"le_factory_name" : @"factory_name",
        @"le_sub_factory_name" : @"sub_factory_name",
        @"le_monthly_salary" : @"monthly_salary",
        @"le_county_id" : @"county_id",
        @"le_sale_type_desc" : @"sale_type_desc",
        @"le_account_date" : @"account_date",
        @"le_order_type" : @"order_type",
        @"le_income_payroll_pic_1" : @"income_payroll_pic_1",
        @"le_pay_state_desc" : @"pay_state_desc",
        @"le_credit_front" : @"credit_front",
        @"le_in_after_sale" : @"in_after_sale",
        @"le_edu_level_desc" : @"edu_level_desc",
        @"le_department" : @"department",
        @"le_position_desc" : @"position_desc",
        @"le_pay_state" : @"pay_state",
        @"le_check_result" : @"check_result",
        @"le_delivery_mobile" : @"delivery_mobile",
        @"le_factory_tel" : @"factory_tel",
        @"le_test_flag" : @"test_flag",
        @"le_user_subtype" : @"user_subtype",
        @"le_is_draw_failed_flag" : @"is_draw_failed_flag",
        @"le_city_name" : @"city_name",
        @"le_order_out_ex" : @"order_out_ex",
        @"le_income_payroll_pic_2" : @"income_payroll_pic_2",
        @"le_social_security_detail_pic" : @"social_security_detail_pic",
        @"le_total_capital" : @"total_capital",
        @"le_self_validate_flag" : @"self_validate_flag",
        @"le_arrive_time" : @"arrive_time",
        @"le_total_handling_fee" : @"total_handling_fee",
        @"le_order_ex_cancel_flag" : @"order_ex_cancel_flag",
        @"le_position" : @"position",

    };
}
@end


@implementation MJTestModel_PocketOrderInfo_OrderInfo


-(instancetype)init{
    self = [super init];
    if (self) {
        self.le_sku_pic = [[NSMutableArray alloc] init];

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{
        @"le_sku_pic" : @"NSString",

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{
        @"le_product_info" : @"product_info",
        @"le_sku_pic" : @"sku_pic",
        @"le_sku_id" : @"sku_id",
        @"le_quantity" : @"quantity",

    };
}
@end


