// Generated by the LeJson.py,  DO NOT EDIT!
// Feedback to iwanglian@github.com,  DO NOT EDIT!

// Created by alick on 2016-05-23 13:26:59,  DO NOT EDIT!

#import "TestModel.h"

@implementation TestModel


-(instancetype)init{
    self = [super init];
    if (self) {

    }
    return self;
}
    
+ (NSDictionary *)mj_objectClassInArray{
   return @{

    };
}


+ (NSDictionary *)mj_replacedKeyFromPropertyName{
   return @{

    };
}
@end


