// Generated by the LeJson.py,  DO NOT EDIT!
// Feedback to iwanglian@github.com,  DO NOT EDIT!

// Created by alick on 2016-05-23 13:26:59,  DO NOT EDIT!

#import <Foundation/Foundation.h>


@interface TestModel : NSObject 
@property (nonatomic, assign) int a;
@property (nonatomic, retain) NSString* b;
@end


