import getpass
import time, types

s_intern_cls_list = ["NSNumber", "NSString", "NSMutableArray"]

s_objc_keyword_replace = {'id': 'ID',
                          'description': 'DESCRIPTION'}
s_objc_dialect_list = ['mj', 'mt', 'yy']
s_java_dialect_list = ['gs', 'fj', 'jc', 'ls']

s_max_int32 = 2147483647


def leType(value):
    value_type = type(value)
    if value_type == types.IntType:
        if value > s_max_int32 or value < -1 * s_max_int32:
            return types.LongType
    return value_type


def u2C(word):
    if (len(word)) == 0:
        return ""
    parts = word.split('_')
    result = ""
    for part in parts:
        result += cap(part)
    return result


def u2c(word):
    result = u2C(word)
    return lcap(result)


def cap(word):
    return word[0].upper() + word[1:]


def lcap(word):
    return word[0].lower() + word[1:]


ISOTIMEFORMAT = '%Y-%m-%d %X'


def gen_desc():
    str = "// Generated by LeJson ,  DO NOT EDIT!\n"
    str += "// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!\n\n"
    str += "// Created by " + getpass.getuser() + " on " + time.strftime(ISOTIMEFORMAT,
                                                                         time.localtime()) + ",  DO NOT EDIT!\n\n"
    return str
