// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 16:41:33,  DO NOT EDIT!

package com.github.iwanglian.lejson.model;

import java.util.List;
import com.alibaba.fastjson.annotation.JSONField;

public class FJTestModel {
	@JSONField(name = "date")
	public String date; 
	@JSONField(name = "top_stories")
	public List<TopStories> topStories; 
	@JSONField(name = "stories")
	public List<Stories> stories; 

	public static class TopStories {
		@JSONField(name = "image")
		public String image; 
		@JSONField(name = "type")
		public int type; 
		@JSONField(name = "id")
		public int ID; 
		@JSONField(name = "ga_prefix")
		public String gaPrefix; 
		@JSONField(name = "title")
		public String title; 
	}
	

	public static class Stories {
		@JSONField(name = "images")
		public List<String> images; 
		@JSONField(name = "type")
		public int type; 
		@JSONField(name = "id")
		public int ID; 
		@JSONField(name = "ga_prefix")
		public String gaPrefix; 
		@JSONField(name = "title")
		public String title; 
	}
	
}

