// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 15:44:45,  DO NOT EDIT!

package com.github.iwanglian.lejson.model;

import java.util.List;
import com.google.gson.annotations.SerializedName;

public class GSTestModel {
	@SerializedName("white_content")
	private List<String> whiteContent; 
	@SerializedName("jump_config")
	private List<JumpConfig> jumpConfig; 
	@SerializedName("res_info")
	private String resInfo; 
	@SerializedName("bottom_config")
	private List<BottomConfig> bottomConfig; 
	@SerializedName("result")
	private int result; 
	@SerializedName("is_login")
	private int isLogin; 

    public List<String> getWhiteContent() {
        return whiteContent;
    }

    public void setWhiteContent(List<String> whiteContent) {
        this.whiteContent = whiteContent;
    } 

    public List<JumpConfig> getJumpConfig() {
        return jumpConfig;
    }

    public void setJumpConfig(List<JumpConfig> jumpConfig) {
        this.jumpConfig = jumpConfig;
    } 

    public String getResInfo() {
        return resInfo;
    }

    public void setResInfo(String resInfo) {
        this.resInfo = resInfo;
    } 

    public List<BottomConfig> getBottomConfig() {
        return bottomConfig;
    }

    public void setBottomConfig(List<BottomConfig> bottomConfig) {
        this.bottomConfig = bottomConfig;
    } 

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    } 

    public int getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(int isLogin) {
        this.isLogin = isLogin;
    } 

	public static class JumpConfig {
		@SerializedName("title_on_color")
		private String titleOnColor; 
		@SerializedName("title_color")
		private String titleColor; 
		@SerializedName("big_img_on_url")
		private String bigImgOnUrl; 
		@SerializedName("title")
		private String title; 
		@SerializedName("url")
		private String url; 
		@SerializedName("start_version")
		private String startVersion; 
		@SerializedName("end_version")
		private String endVersion; 
		@SerializedName("img_on_url")
		private String imgOnUrl; 
		@SerializedName("big_img_url")
		private String bigImgUrl; 
		@SerializedName("config_key")
		private String configKey; 
		@SerializedName("arguments")
		private String arguments; 
		@SerializedName("key")
		private String key; 
		@SerializedName("h5_enabled")
		private boolean h5Enabled; 
		@SerializedName("position")
		private String position; 
		@SerializedName("img_url")
		private String imgUrl; 
		@SerializedName("regular")
		private String regular; 
	
	    public String getTitleOnColor() {
	        return titleOnColor;
	    }
	
	    public void setTitleOnColor(String titleOnColor) {
	        this.titleOnColor = titleOnColor;
	    } 
	
	    public String getTitleColor() {
	        return titleColor;
	    }
	
	    public void setTitleColor(String titleColor) {
	        this.titleColor = titleColor;
	    } 
	
	    public String getBigImgOnUrl() {
	        return bigImgOnUrl;
	    }
	
	    public void setBigImgOnUrl(String bigImgOnUrl) {
	        this.bigImgOnUrl = bigImgOnUrl;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	
	    public String getUrl() {
	        return url;
	    }
	
	    public void setUrl(String url) {
	        this.url = url;
	    } 
	
	    public String getStartVersion() {
	        return startVersion;
	    }
	
	    public void setStartVersion(String startVersion) {
	        this.startVersion = startVersion;
	    } 
	
	    public String getEndVersion() {
	        return endVersion;
	    }
	
	    public void setEndVersion(String endVersion) {
	        this.endVersion = endVersion;
	    } 
	
	    public String getImgOnUrl() {
	        return imgOnUrl;
	    }
	
	    public void setImgOnUrl(String imgOnUrl) {
	        this.imgOnUrl = imgOnUrl;
	    } 
	
	    public String getBigImgUrl() {
	        return bigImgUrl;
	    }
	
	    public void setBigImgUrl(String bigImgUrl) {
	        this.bigImgUrl = bigImgUrl;
	    } 
	
	    public String getConfigKey() {
	        return configKey;
	    }
	
	    public void setConfigKey(String configKey) {
	        this.configKey = configKey;
	    } 
	
	    public String getArguments() {
	        return arguments;
	    }
	
	    public void setArguments(String arguments) {
	        this.arguments = arguments;
	    } 
	
	    public String getKey() {
	        return key;
	    }
	
	    public void setKey(String key) {
	        this.key = key;
	    } 
	
	    public boolean getH5Enabled() {
	        return h5Enabled;
	    }
	
	    public void setH5Enabled(boolean h5Enabled) {
	        this.h5Enabled = h5Enabled;
	    } 
	
	    public String getPosition() {
	        return position;
	    }
	
	    public void setPosition(String position) {
	        this.position = position;
	    } 
	
	    public String getImgUrl() {
	        return imgUrl;
	    }
	
	    public void setImgUrl(String imgUrl) {
	        this.imgUrl = imgUrl;
	    } 
	
	    public String getRegular() {
	        return regular;
	    }
	
	    public void setRegular(String regular) {
	        this.regular = regular;
	    } 
	}
	

	public static class BottomConfig {
		@SerializedName("title_on_color")
		private String titleOnColor; 
		@SerializedName("title_color")
		private String titleColor; 
		@SerializedName("big_img_on_url")
		private String bigImgOnUrl; 
		@SerializedName("title")
		private String title; 
		@SerializedName("url")
		private String url; 
		@SerializedName("start_version")
		private String startVersion; 
		@SerializedName("tag")
		private String tag; 
		@SerializedName("end_version")
		private String endVersion; 
		@SerializedName("img_on_url")
		private String imgOnUrl; 
		@SerializedName("big_img_url")
		private String bigImgUrl; 
		@SerializedName("config_key")
		private String configKey; 
		@SerializedName("arguments")
		private String arguments; 
		@SerializedName("key")
		private String key; 
		@SerializedName("h5_enabled")
		private boolean h5Enabled; 
		@SerializedName("position")
		private String position; 
		@SerializedName("img_url")
		private String imgUrl; 
		@SerializedName("regular")
		private String regular; 
	
	    public String getTitleOnColor() {
	        return titleOnColor;
	    }
	
	    public void setTitleOnColor(String titleOnColor) {
	        this.titleOnColor = titleOnColor;
	    } 
	
	    public String getTitleColor() {
	        return titleColor;
	    }
	
	    public void setTitleColor(String titleColor) {
	        this.titleColor = titleColor;
	    } 
	
	    public String getBigImgOnUrl() {
	        return bigImgOnUrl;
	    }
	
	    public void setBigImgOnUrl(String bigImgOnUrl) {
	        this.bigImgOnUrl = bigImgOnUrl;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	
	    public String getUrl() {
	        return url;
	    }
	
	    public void setUrl(String url) {
	        this.url = url;
	    } 
	
	    public String getStartVersion() {
	        return startVersion;
	    }
	
	    public void setStartVersion(String startVersion) {
	        this.startVersion = startVersion;
	    } 
	
	    public String getTag() {
	        return tag;
	    }
	
	    public void setTag(String tag) {
	        this.tag = tag;
	    } 
	
	    public String getEndVersion() {
	        return endVersion;
	    }
	
	    public void setEndVersion(String endVersion) {
	        this.endVersion = endVersion;
	    } 
	
	    public String getImgOnUrl() {
	        return imgOnUrl;
	    }
	
	    public void setImgOnUrl(String imgOnUrl) {
	        this.imgOnUrl = imgOnUrl;
	    } 
	
	    public String getBigImgUrl() {
	        return bigImgUrl;
	    }
	
	    public void setBigImgUrl(String bigImgUrl) {
	        this.bigImgUrl = bigImgUrl;
	    } 
	
	    public String getConfigKey() {
	        return configKey;
	    }
	
	    public void setConfigKey(String configKey) {
	        this.configKey = configKey;
	    } 
	
	    public String getArguments() {
	        return arguments;
	    }
	
	    public void setArguments(String arguments) {
	        this.arguments = arguments;
	    } 
	
	    public String getKey() {
	        return key;
	    }
	
	    public void setKey(String key) {
	        this.key = key;
	    } 
	
	    public boolean getH5Enabled() {
	        return h5Enabled;
	    }
	
	    public void setH5Enabled(boolean h5Enabled) {
	        this.h5Enabled = h5Enabled;
	    } 
	
	    public String getPosition() {
	        return position;
	    }
	
	    public void setPosition(String position) {
	        this.position = position;
	    } 
	
	    public String getImgUrl() {
	        return imgUrl;
	    }
	
	    public void setImgUrl(String imgUrl) {
	        this.imgUrl = imgUrl;
	    } 
	
	    public String getRegular() {
	        return regular;
	    }
	
	    public void setRegular(String regular) {
	        this.regular = regular;
	    } 
	}
	
}

