// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 16:41:33,  DO NOT EDIT!

package com.github.iwanglian.lejson.model;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

public class JCTestModel {
	@JsonProperty("date")
	public String date; 
	@JsonProperty("top_stories")
	public List<TopStories> topStories; 
	@JsonProperty("stories")
	public List<Stories> stories; 

	public static class TopStories {
		@JsonProperty("image")
		public String image; 
		@JsonProperty("type")
		public int type; 
		@JsonProperty("id")
		public int ID; 
		@JsonProperty("ga_prefix")
		public String gaPrefix; 
		@JsonProperty("title")
		public String title; 
	}
	

	public static class Stories {
		@JsonProperty("images")
		public List<String> images; 
		@JsonProperty("type")
		public int type; 
		@JsonProperty("id")
		public int ID; 
		@JsonProperty("ga_prefix")
		public String gaPrefix; 
		@JsonProperty("title")
		public String title; 
	}
	
}

