// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-06-01 15:44:45,  DO NOT EDIT!

package com.github.iwanglian.lejson.model;

import java.util.List;
import java.util.ArrayList;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;



public class JOTestModel {
	private List<String> whiteContent; 
	private List<JumpConfig> jumpConfig; 
	private String resInfo; 
	private List<BottomConfig> bottomConfig; 
	private int result; 
	private int isLogin; 

    public static JOTestModel objectFromString(String string) throws JSONException {
        JSONObject jsonObject = new JSONObject(string);
        return objectFromJSON(jsonObject);
    }

    public static String stringFromObject(JOTestModel object) throws JSONException {
        JSONObject jsonObject = JSONFromObject(object);
        return jsonObject.toString();
    }

	public static JOTestModel objectFromJSON(JSONObject jsonObject) {
	    JOTestModel object = new JOTestModel();
	
		if (jsonObject.optJSONArray("white_content") != null) {
		    JSONArray jsonArray = jsonObject.optJSONArray("white_content");
		    List<String> list = new ArrayList<>();
		    for (int i = 0; i < jsonArray.length(); i++) {
				String item = jsonArray.optString(i);
				list.add(item);
		    }
		    object.whiteContent = list;
		}
		
		if (jsonObject.optJSONArray("jump_config") != null) {
		    JSONArray jsonArray = jsonObject.optJSONArray("jump_config");
		    List<JumpConfig> list = new ArrayList<>();
		    for (int i = 0; i < jsonArray.length(); i++) {
				JSONObject jsonObj = jsonArray.optJSONObject(i);
				if(jsonObj!=null) {
				    JumpConfig item = JumpConfig.objectFromJSON(jsonObj);
				    list.add(item);
				}
		    }
		    object.jumpConfig = list;
		}
		
		object.resInfo = jsonObject.optString("res_info");
		if (jsonObject.optJSONArray("bottom_config") != null) {
		    JSONArray jsonArray = jsonObject.optJSONArray("bottom_config");
		    List<BottomConfig> list = new ArrayList<>();
		    for (int i = 0; i < jsonArray.length(); i++) {
				JSONObject jsonObj = jsonArray.optJSONObject(i);
				if(jsonObj!=null) {
				    BottomConfig item = BottomConfig.objectFromJSON(jsonObj);
				    list.add(item);
				}
		    }
		    object.bottomConfig = list;
		}
		
		object.result = jsonObject.optInt("result");
		object.isLogin = jsonObject.optInt("is_login");
		return object;
	}
	
	public static JSONObject JSONFromObject(JOTestModel object) {
	    JSONObject jsonObject = new JSONObject();
	    try { 
			if(object.whiteContent!=null){
			    List<String> list = object.whiteContent;
			    JSONArray jsonArray = new JSONArray();
				for (String item : list) {
				    jsonArray.put(item);
				} 
			    jsonObject.put("white_content",jsonArray);
			} 
			if(object.jumpConfig!=null){
			    List<JumpConfig> list = object.jumpConfig;
			    JSONArray jsonArray = new JSONArray();
				for (JumpConfig item : list) {
				    JSONObject jsonObj = JumpConfig.JSONFromObject(item);
				    jsonArray.put(jsonObj);
				} 
			    jsonObject.put("jump_config",jsonArray);
			} 
			jsonObject.put("res_info", object.resInfo);
			if(object.bottomConfig!=null){
			    List<BottomConfig> list = object.bottomConfig;
			    JSONArray jsonArray = new JSONArray();
				for (BottomConfig item : list) {
				    JSONObject jsonObj = BottomConfig.JSONFromObject(item);
				    jsonArray.put(jsonObj);
				} 
			    jsonObject.put("bottom_config",jsonArray);
			} 
			jsonObject.put("result", object.result);
			jsonObject.put("is_login", object.isLogin);
		} catch (JSONException e) {
		    e.printStackTrace();
		}
		
		return jsonObject; 
	}

    public List<String> getWhiteContent() {
        return whiteContent;
    }

    public void setWhiteContent(List<String> whiteContent) {
        this.whiteContent = whiteContent;
    } 

    public List<JumpConfig> getJumpConfig() {
        return jumpConfig;
    }

    public void setJumpConfig(List<JumpConfig> jumpConfig) {
        this.jumpConfig = jumpConfig;
    } 

    public String getResInfo() {
        return resInfo;
    }

    public void setResInfo(String resInfo) {
        this.resInfo = resInfo;
    } 

    public List<BottomConfig> getBottomConfig() {
        return bottomConfig;
    }

    public void setBottomConfig(List<BottomConfig> bottomConfig) {
        this.bottomConfig = bottomConfig;
    } 

    public int getResult() {
        return result;
    }

    public void setResult(int result) {
        this.result = result;
    } 

    public int getIsLogin() {
        return isLogin;
    }

    public void setIsLogin(int isLogin) {
        this.isLogin = isLogin;
    } 

	public static class JumpConfig {
		private String titleOnColor; 
		private String titleColor; 
		private String bigImgOnUrl; 
		private String title; 
		private String url; 
		private String startVersion; 
		private String endVersion; 
		private String imgOnUrl; 
		private String bigImgUrl; 
		private String configKey; 
		private String arguments; 
		private String key; 
		private boolean h5Enabled; 
		private String position; 
		private String imgUrl; 
		private String regular; 
	
		public static JumpConfig objectFromJSON(JSONObject jsonObject) {
		    JumpConfig object = new JumpConfig();
		
			object.titleOnColor = jsonObject.optString("title_on_color");
			object.titleColor = jsonObject.optString("title_color");
			object.bigImgOnUrl = jsonObject.optString("big_img_on_url");
			object.title = jsonObject.optString("title");
			object.url = jsonObject.optString("url");
			object.startVersion = jsonObject.optString("start_version");
			object.endVersion = jsonObject.optString("end_version");
			object.imgOnUrl = jsonObject.optString("img_on_url");
			object.bigImgUrl = jsonObject.optString("big_img_url");
			object.configKey = jsonObject.optString("config_key");
			object.arguments = jsonObject.optString("arguments");
			object.key = jsonObject.optString("key");
			object.h5Enabled = jsonObject.optBoolean("h5_enabled");
			object.position = jsonObject.optString("position");
			object.imgUrl = jsonObject.optString("img_url");
			object.regular = jsonObject.optString("regular");
			return object;
		}
		
		public static JSONObject JSONFromObject(JumpConfig object) {
		    JSONObject jsonObject = new JSONObject();
		    try { 
				jsonObject.put("title_on_color", object.titleOnColor);
				jsonObject.put("title_color", object.titleColor);
				jsonObject.put("big_img_on_url", object.bigImgOnUrl);
				jsonObject.put("title", object.title);
				jsonObject.put("url", object.url);
				jsonObject.put("start_version", object.startVersion);
				jsonObject.put("end_version", object.endVersion);
				jsonObject.put("img_on_url", object.imgOnUrl);
				jsonObject.put("big_img_url", object.bigImgUrl);
				jsonObject.put("config_key", object.configKey);
				jsonObject.put("arguments", object.arguments);
				jsonObject.put("key", object.key);
				jsonObject.put("h5_enabled", object.h5Enabled);
				jsonObject.put("position", object.position);
				jsonObject.put("img_url", object.imgUrl);
				jsonObject.put("regular", object.regular);
			} catch (JSONException e) {
			    e.printStackTrace();
			}
			
			return jsonObject; 
		}
	
	    public String getTitleOnColor() {
	        return titleOnColor;
	    }
	
	    public void setTitleOnColor(String titleOnColor) {
	        this.titleOnColor = titleOnColor;
	    } 
	
	    public String getTitleColor() {
	        return titleColor;
	    }
	
	    public void setTitleColor(String titleColor) {
	        this.titleColor = titleColor;
	    } 
	
	    public String getBigImgOnUrl() {
	        return bigImgOnUrl;
	    }
	
	    public void setBigImgOnUrl(String bigImgOnUrl) {
	        this.bigImgOnUrl = bigImgOnUrl;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	
	    public String getUrl() {
	        return url;
	    }
	
	    public void setUrl(String url) {
	        this.url = url;
	    } 
	
	    public String getStartVersion() {
	        return startVersion;
	    }
	
	    public void setStartVersion(String startVersion) {
	        this.startVersion = startVersion;
	    } 
	
	    public String getEndVersion() {
	        return endVersion;
	    }
	
	    public void setEndVersion(String endVersion) {
	        this.endVersion = endVersion;
	    } 
	
	    public String getImgOnUrl() {
	        return imgOnUrl;
	    }
	
	    public void setImgOnUrl(String imgOnUrl) {
	        this.imgOnUrl = imgOnUrl;
	    } 
	
	    public String getBigImgUrl() {
	        return bigImgUrl;
	    }
	
	    public void setBigImgUrl(String bigImgUrl) {
	        this.bigImgUrl = bigImgUrl;
	    } 
	
	    public String getConfigKey() {
	        return configKey;
	    }
	
	    public void setConfigKey(String configKey) {
	        this.configKey = configKey;
	    } 
	
	    public String getArguments() {
	        return arguments;
	    }
	
	    public void setArguments(String arguments) {
	        this.arguments = arguments;
	    } 
	
	    public String getKey() {
	        return key;
	    }
	
	    public void setKey(String key) {
	        this.key = key;
	    } 
	
	    public boolean getH5Enabled() {
	        return h5Enabled;
	    }
	
	    public void setH5Enabled(boolean h5Enabled) {
	        this.h5Enabled = h5Enabled;
	    } 
	
	    public String getPosition() {
	        return position;
	    }
	
	    public void setPosition(String position) {
	        this.position = position;
	    } 
	
	    public String getImgUrl() {
	        return imgUrl;
	    }
	
	    public void setImgUrl(String imgUrl) {
	        this.imgUrl = imgUrl;
	    } 
	
	    public String getRegular() {
	        return regular;
	    }
	
	    public void setRegular(String regular) {
	        this.regular = regular;
	    } 
	}
	

	public static class BottomConfig {
		private String titleOnColor; 
		private String titleColor; 
		private String bigImgOnUrl; 
		private String title; 
		private String url; 
		private String startVersion; 
		private String tag; 
		private String endVersion; 
		private String imgOnUrl; 
		private String bigImgUrl; 
		private String configKey; 
		private String arguments; 
		private String key; 
		private boolean h5Enabled; 
		private String position; 
		private String imgUrl; 
		private String regular; 
	
		public static BottomConfig objectFromJSON(JSONObject jsonObject) {
		    BottomConfig object = new BottomConfig();
		
			object.titleOnColor = jsonObject.optString("title_on_color");
			object.titleColor = jsonObject.optString("title_color");
			object.bigImgOnUrl = jsonObject.optString("big_img_on_url");
			object.title = jsonObject.optString("title");
			object.url = jsonObject.optString("url");
			object.startVersion = jsonObject.optString("start_version");
			object.tag = jsonObject.optString("tag");
			object.endVersion = jsonObject.optString("end_version");
			object.imgOnUrl = jsonObject.optString("img_on_url");
			object.bigImgUrl = jsonObject.optString("big_img_url");
			object.configKey = jsonObject.optString("config_key");
			object.arguments = jsonObject.optString("arguments");
			object.key = jsonObject.optString("key");
			object.h5Enabled = jsonObject.optBoolean("h5_enabled");
			object.position = jsonObject.optString("position");
			object.imgUrl = jsonObject.optString("img_url");
			object.regular = jsonObject.optString("regular");
			return object;
		}
		
		public static JSONObject JSONFromObject(BottomConfig object) {
		    JSONObject jsonObject = new JSONObject();
		    try { 
				jsonObject.put("title_on_color", object.titleOnColor);
				jsonObject.put("title_color", object.titleColor);
				jsonObject.put("big_img_on_url", object.bigImgOnUrl);
				jsonObject.put("title", object.title);
				jsonObject.put("url", object.url);
				jsonObject.put("start_version", object.startVersion);
				jsonObject.put("tag", object.tag);
				jsonObject.put("end_version", object.endVersion);
				jsonObject.put("img_on_url", object.imgOnUrl);
				jsonObject.put("big_img_url", object.bigImgUrl);
				jsonObject.put("config_key", object.configKey);
				jsonObject.put("arguments", object.arguments);
				jsonObject.put("key", object.key);
				jsonObject.put("h5_enabled", object.h5Enabled);
				jsonObject.put("position", object.position);
				jsonObject.put("img_url", object.imgUrl);
				jsonObject.put("regular", object.regular);
			} catch (JSONException e) {
			    e.printStackTrace();
			}
			
			return jsonObject; 
		}
	
	    public String getTitleOnColor() {
	        return titleOnColor;
	    }
	
	    public void setTitleOnColor(String titleOnColor) {
	        this.titleOnColor = titleOnColor;
	    } 
	
	    public String getTitleColor() {
	        return titleColor;
	    }
	
	    public void setTitleColor(String titleColor) {
	        this.titleColor = titleColor;
	    } 
	
	    public String getBigImgOnUrl() {
	        return bigImgOnUrl;
	    }
	
	    public void setBigImgOnUrl(String bigImgOnUrl) {
	        this.bigImgOnUrl = bigImgOnUrl;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	
	    public String getUrl() {
	        return url;
	    }
	
	    public void setUrl(String url) {
	        this.url = url;
	    } 
	
	    public String getStartVersion() {
	        return startVersion;
	    }
	
	    public void setStartVersion(String startVersion) {
	        this.startVersion = startVersion;
	    } 
	
	    public String getTag() {
	        return tag;
	    }
	
	    public void setTag(String tag) {
	        this.tag = tag;
	    } 
	
	    public String getEndVersion() {
	        return endVersion;
	    }
	
	    public void setEndVersion(String endVersion) {
	        this.endVersion = endVersion;
	    } 
	
	    public String getImgOnUrl() {
	        return imgOnUrl;
	    }
	
	    public void setImgOnUrl(String imgOnUrl) {
	        this.imgOnUrl = imgOnUrl;
	    } 
	
	    public String getBigImgUrl() {
	        return bigImgUrl;
	    }
	
	    public void setBigImgUrl(String bigImgUrl) {
	        this.bigImgUrl = bigImgUrl;
	    } 
	
	    public String getConfigKey() {
	        return configKey;
	    }
	
	    public void setConfigKey(String configKey) {
	        this.configKey = configKey;
	    } 
	
	    public String getArguments() {
	        return arguments;
	    }
	
	    public void setArguments(String arguments) {
	        this.arguments = arguments;
	    } 
	
	    public String getKey() {
	        return key;
	    }
	
	    public void setKey(String key) {
	        this.key = key;
	    } 
	
	    public boolean getH5Enabled() {
	        return h5Enabled;
	    }
	
	    public void setH5Enabled(boolean h5Enabled) {
	        this.h5Enabled = h5Enabled;
	    } 
	
	    public String getPosition() {
	        return position;
	    }
	
	    public void setPosition(String position) {
	        this.position = position;
	    } 
	
	    public String getImgUrl() {
	        return imgUrl;
	    }
	
	    public void setImgUrl(String imgUrl) {
	        this.imgUrl = imgUrl;
	    } 
	
	    public String getRegular() {
	        return regular;
	    }
	
	    public void setRegular(String regular) {
	        this.regular = regular;
	    } 
	}
	
}

