// Generated by LeJson ,  DO NOT EDIT!
// Feedback to https://github.com/iwanglian/LeJson/issues,  DO NOT EDIT!

// Created by alick on 2016-05-27 12:49:52,  DO NOT EDIT!

package com.github.iwanglian.lejson.model;

import java.util.List;
import com.bluelinelabs.logansquare.annotation.JsonField;
import com.bluelinelabs.logansquare.annotation.JsonObject;
@JsonObject

public class LSTestModel {
	@JsonField(name = "date")
	private String date; 
	@JsonField(name = "top_stories")
	private List<TopStories>  topStories; 
	@JsonField(name = "stories")
	private List<Stories>  stories; 

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    } 

    public List<TopStories>  getTopStories() {
        return topStories;
    }

    public void setTopStories(List<TopStories>  topStories) {
        this.topStories = topStories;
    } 

    public List<Stories>  getStories() {
        return stories;
    }

    public void setStories(List<Stories>  stories) {
        this.stories = stories;
    } 
@JsonObject
	
	public static class TopStories {
		@JsonField(name = "image")
		private String image; 
		@JsonField(name = "type")
		private int type; 
		@JsonField(name = "id")
		private int ID; 
		@JsonField(name = "ga_prefix")
		private String gaPrefix; 
		@JsonField(name = "title")
		private String title; 
	
	    public String getImage() {
	        return image;
	    }
	
	    public void setImage(String image) {
	        this.image = image;
	    } 
	
	    public int getType() {
	        return type;
	    }
	
	    public void setType(int type) {
	        this.type = type;
	    } 
	
	    public int getID() {
	        return ID;
	    }
	
	    public void setID(int ID) {
	        this.ID = ID;
	    } 
	
	    public String getGaPrefix() {
	        return gaPrefix;
	    }
	
	    public void setGaPrefix(String gaPrefix) {
	        this.gaPrefix = gaPrefix;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	}
	
@JsonObject
	
	public static class Stories {
		@JsonField(name = "images")
		private List<String>  images; 
		@JsonField(name = "type")
		private int type; 
		@JsonField(name = "id")
		private int ID; 
		@JsonField(name = "ga_prefix")
		private String gaPrefix; 
		@JsonField(name = "title")
		private String title; 
	
	    public List<String>  getImages() {
	        return images;
	    }
	
	    public void setImages(List<String>  images) {
	        this.images = images;
	    } 
	
	    public int getType() {
	        return type;
	    }
	
	    public void setType(int type) {
	        this.type = type;
	    } 
	
	    public int getID() {
	        return ID;
	    }
	
	    public void setID(int ID) {
	        this.ID = ID;
	    } 
	
	    public String getGaPrefix() {
	        return gaPrefix;
	    }
	
	    public void setGaPrefix(String gaPrefix) {
	        this.gaPrefix = gaPrefix;
	    } 
	
	    public String getTitle() {
	        return title;
	    }
	
	    public void setTitle(String title) {
	        this.title = title;
	    } 
	}
	
}

